#!/usr/bin/env python3
"""
build_functions_kb_blade.py - Blade template catalogue for KM. Closes
part C of #58.

Walks .blade.php under /usr/share/nginx/heratio/{packages,resources} and
emits a section per template with @include map, @section/@yield names,
and @push targets so the KM can answer "where is _foo included from?"
or "which partials wire into the @section('main') slot?".

Output: /opt/ai/km/auto_functions_kb_blade.md

@copyright  Johan Pieterse / Plain Sailing
@license    AGPL-3.0-or-later
"""

from __future__ import annotations
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

HERATIO = "/usr/share/nginx/heratio"
ROOTS   = ["packages", "resources"]
SKIPS   = {"vendor", "node_modules", "cache", "tests", "Tests", "dist", "build", ".git"}

OUT_PATH = "/opt/ai/km/auto_functions_kb_blade.md"

RE_INCLUDE = re.compile(r"@include\(\s*['\"]([^'\"]+)['\"]")
RE_EXTENDS = re.compile(r"@extends\(\s*['\"]([^'\"]+)['\"]")
RE_SECTION = re.compile(r"@section\(\s*['\"]([^'\"]+)['\"]")
RE_YIELD   = re.compile(r"@yield\(\s*['\"]([^'\"]+)['\"]")
RE_PUSH    = re.compile(r"@push\(\s*['\"]([^'\"]+)['\"]")
RE_STACK   = re.compile(r"@stack\(\s*['\"]([^'\"]+)['\"]")
RE_USE     = re.compile(r"@(?:component|livewire|x-)\(?\s*['\"]?([A-Za-z0-9_:.-]+)")


def walk_blades(root: str) -> list[Path]:
    out = []
    for r in ROOTS:
        base = Path(root) / r
        if not base.exists(): continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames if d not in SKIPS]
            for f in filenames:
                if f.endswith('.blade.php'):
                    out.append(Path(dirpath) / f)
    return out


def parse_blade(path: Path, source: str) -> dict:
    return {
        'file':     str(path),
        'lines':    source.count('\n') + 1,
        'extends':  RE_EXTENDS.findall(source),
        'includes': sorted(set(RE_INCLUDE.findall(source))),
        'sections': sorted(set(RE_SECTION.findall(source))),
        'yields':   sorted(set(RE_YIELD.findall(source))),
        'pushes':   sorted(set(RE_PUSH.findall(source))),
        'stacks':   sorted(set(RE_STACK.findall(source))),
        'uses':     sorted(set(RE_USE.findall(source))),
    }


def render(records: list[dict]) -> str:
    # Inverse include map: which templates include X?
    included_by: dict[str, list[str]] = defaultdict(list)
    for r in records:
        for inc in r['includes']:
            included_by[inc].append(r['file'])

    out = ['# Heratio Blade template catalogue', '',
           'Auto-generated by `/opt/ai/km/build_functions_kb_blade.py`. Closes #58 part C.', '',
           f'**Coverage:** {len(records)} blade templates.', '']

    # Most-included partials (top 30) - useful overview.
    most = sorted(included_by.items(), key=lambda kv: -len(kv[1]))[:30]
    if most:
        out += ['## Most-included partials (top 30)', '']
        for name, sites in most:
            out.append(f'- `{name}` — included from {len(sites)} site(s)')
        out += ['']

    for r in sorted(records, key=lambda x: x['file']):
        out.append(f'## {r["file"]}')
        out.append('')
        out.append(f"**Lines:** {r['lines']}  ")
        if r['extends']:  out.append(f"**Extends:** " + ', '.join(f'`{x}`' for x in r['extends']))
        if r['sections']: out.append(f"**Sections:** " + ', '.join(f'`{x}`' for x in r['sections']))
        if r['yields']:   out.append(f"**Yields:** "   + ', '.join(f'`{x}`' for x in r['yields']))
        if r['pushes']:   out.append(f"**Pushes:** "   + ', '.join(f'`{x}`' for x in r['pushes']))
        if r['stacks']:   out.append(f"**Stacks:** "   + ', '.join(f'`{x}`' for x in r['stacks']))
        if r['includes']:
            out.append(f"**Includes:** " + ', '.join(f'`{x}`' for x in r['includes'][:40]))
        if r['uses']:
            out.append(f"**Components:** " + ', '.join(f'`{x}`' for x in r['uses'][:20]))
        cb = included_by.get(r['file'], [])
        # Best-effort - only matches by full path; the @include uses dotted view names.
        if cb:
            out.append(f"**Included by:** " + ', '.join(f'`{x}`' for x in cb[:10]))
        out.append('')
    return '\n'.join(out)


def main() -> int:
    files = walk_blades(HERATIO)
    print(f"[build_functions_kb_blade] {len(files)} .blade.php files", file=sys.stderr)
    records: list[dict] = []
    for path in files:
        try:
            records.append(parse_blade(path, path.read_text(encoding='utf-8', errors='replace')))
        except Exception as e:
            print(f"[build_functions_kb_blade] WARN: {path}: {e}", file=sys.stderr)
    md = render(records)
    Path(OUT_PATH).write_text(md, encoding='utf-8')
    print(f"[build_functions_kb_blade] {len(records)} blades; wrote {OUT_PATH} ({len(md):,} bytes)", file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
