#!/usr/bin/env python3
"""
build_functions_kb_py.py - Python catalogue for KM. Closes part D of #58.

Walks /opt/ai/km (the operator-side ingest + audit + build scripts) since
the Heratio repo itself has no first-party Python (Cantaloupe + Ollama +
KM stack are external). Uses the stdlib `ast` module - safer than regex
for Python.

Output: /opt/ai/km/auto_functions_kb_py.md

@copyright  Johan Pieterse / Plain Sailing
@license    AGPL-3.0-or-later
"""

from __future__ import annotations
import ast
import os
import sys
from collections import defaultdict
from pathlib import Path

ROOTS    = ["/opt/ai/km"]
SKIPS    = {"__pycache__", ".git", "venv", ".venv", "site-packages"}

OUT_PATH = "/opt/ai/km/auto_functions_kb_py.md"


def first_sentence(doc: str | None) -> str:
    if not doc: return ''
    text = doc.strip().split('\n\n', 1)[0].strip()
    text = text.replace('\n', ' ').strip()
    return text[:500]


def sig(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str:
    parts = []
    args = node.args
    posonly = getattr(args, 'posonlyargs', [])
    for a in posonly + args.args:
        s = a.arg
        if a.annotation is not None:
            try: s += f': {ast.unparse(a.annotation)}'
            except Exception: pass
        parts.append(s)
    if args.vararg:
        parts.append(f'*{args.vararg.arg}')
    for a in args.kwonlyargs:
        s = a.arg
        if a.annotation is not None:
            try: s += f': {ast.unparse(a.annotation)}'
            except Exception: pass
        parts.append(s)
    if args.kwarg:
        parts.append(f'**{args.kwarg.arg}')
    out = '(' + ', '.join(parts) + ')'
    if node.returns is not None:
        try: out += f' -> {ast.unparse(node.returns)}'
        except Exception: pass
    return out


def walk_py(roots: list[str]) -> list[Path]:
    out = []
    for r in roots:
        base = Path(r)
        if not base.exists(): continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames if d not in SKIPS]
            for f in filenames:
                if f.endswith('.py'):
                    out.append(Path(dirpath) / f)
    return out


def parse_py(path: Path) -> list[dict]:
    try:
        source = path.read_text(encoding='utf-8', errors='replace')
        tree = ast.parse(source, filename=str(path))
    except Exception as e:
        print(f"[build_functions_kb_py] WARN: {path}: {e}", file=sys.stderr)
        return []
    out: list[dict] = []

    def walk(n, cls=''):
        for c in ast.iter_child_nodes(n):
            if isinstance(c, ast.ClassDef):
                walk(c, cls=c.name)
            elif isinstance(c, (ast.FunctionDef, ast.AsyncFunctionDef)):
                out.append({
                    'cls':  cls,
                    'name': c.name,
                    'kind': 'async def' if isinstance(c, ast.AsyncFunctionDef) else 'def',
                    'sig':  sig(c),
                    'doc':  first_sentence(ast.get_docstring(c)),
                    'file': str(path),
                    'line': c.lineno,
                })
                # Walk body for nested functions / methods if it's a class
                walk(c, cls=cls)
            elif isinstance(c, ast.Module):
                walk(c)

    walk(tree)
    return out


def render(records: list[dict]) -> str:
    by_file: dict[str, list[dict]] = defaultdict(list)
    for r in records:
        by_file[r['file']].append(r)
    out = ['# KM Python catalogue', '',
           'Auto-generated by `/opt/ai/km/build_functions_kb_py.py`. Closes #58 part D.',
           'Covers the operator-side ingest, audit, and KB-build scripts under', '`/opt/ai/km/`.', '',
           f'**Coverage:** {len(records)} functions across {len(by_file)} files.', '']
    for file in sorted(by_file):
        out.append(f'# {file}')
        out.append('')
        for r in sorted(by_file[file], key=lambda x: x['line']):
            label = f"{r['cls']}.{r['name']}" if r['cls'] else r['name']
            out.append(f'## {label}')
            out.append('')
            out.append(f"**Kind:** `{r['kind']}`  ")
            out.append(f"**Signature:** `{r['sig']}`  ")
            out.append(f"**File:** `{r['file']}:{r['line']}`  ")
            if r['doc']:
                out.append('')
                out.append(r['doc'])
            out.append('')
    return '\n'.join(out)


def main() -> int:
    files = walk_py(ROOTS)
    print(f"[build_functions_kb_py] {len(files)} Python files", file=sys.stderr)
    records: list[dict] = []
    for path in files:
        records.extend(parse_py(path))
    md = render(records)
    Path(OUT_PATH).write_text(md, encoding='utf-8')
    print(f"[build_functions_kb_py] {len(records)} functions; wrote {OUT_PATH} ({len(md):,} bytes)", file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
