#!/usr/bin/env python3
"""
build_functions_kb_js.py - JavaScript function catalogue for KM. Closes
part B of #58.

Walks JS/TS sources under /usr/share/nginx/heratio/{packages,public,resources}
and extracts named functions, methods, arrow assignments, and class methods.
Skips minified bundles (vendor, *.min.js, dist/, build/, node_modules).

Output: /opt/ai/km/auto_functions_kb_js.md

@copyright  Johan Pieterse / Plain Sailing
@license    AGPL-3.0-or-later
"""

from __future__ import annotations
import os
import re
import sys
from collections import defaultdict
from pathlib import Path

HERATIO = "/usr/share/nginx/heratio"
ROOTS   = ["packages", "public", "resources"]
SKIPS   = {"vendor", "node_modules", "cache", "tests", "Tests", "dist", "build", ".git"}
EXTS    = ('.js', '.mjs', '.ts')

OUT_PATH = "/opt/ai/km/auto_functions_kb_js.md"

# Forms of declaration we care about. ES classes are picked up via the
# method shorthand inside `class { ... }`.
RE_CLASS    = re.compile(r'\bclass\s+([A-Z][A-Za-z0-9_]*)')
RE_FN_DECL  = re.compile(r'\bfunction\s+([A-Za-z_$][\w$]*)\s*\(([^)]*)\)')
RE_FN_EXPR  = re.compile(r'(?:const|let|var)\s+([A-Za-z_$][\w$]*)\s*=\s*(?:async\s*)?(?:function\s*\(([^)]*)\)|\(([^)]*)\)\s*=>)')
RE_METHOD   = re.compile(r'^\s*(?:async\s+)?([A-Za-z_$][\w$]*)\s*\(([^)]*)\)\s*\{', re.M)
RE_DOC      = re.compile(r'/\*\*([\s\S]*?)\*/')


def first_sentence(doc: str | None) -> str:
    if not doc:
        return ''
    text = re.sub(r'^\s*\*\s?', '', doc.strip(), flags=re.M).strip()
    text = re.split(r'\n\s*@', text, maxsplit=1)[0].strip()
    text = re.split(r'(?<=[.!?])\s+', text, maxsplit=1)[0].strip()
    return re.sub(r'\s+', ' ', text)[:500]


def line_of(source: str, idx: int) -> int:
    return source.count('\n', 0, idx) + 1


def doc_before(source: str, idx: int) -> str | None:
    """Find the docblock immediately preceding position idx (skipping whitespace)."""
    head = source[:idx]
    m = re.search(r'/\*\*([\s\S]*?)\*/\s*$', head)
    return f'/**{m.group(1)}*/' if m else None


def parse_js(path: Path, source: str) -> list[dict]:
    out: list[dict] = []
    file = str(path)
    classes = [(m.group(1), m.start()) for m in RE_CLASS.finditer(source)]
    cls_for = lambda pos: next((c for c, s in reversed(classes) if s < pos), '')

    seen = set()
    for m in RE_FN_DECL.finditer(source):
        name, params = m.group(1), re.sub(r'\s+', ' ', m.group(2).strip())
        key = (file, m.start(), name)
        if key in seen: continue
        seen.add(key)
        out.append({
            'name': name, 'kind': 'function', 'params': params,
            'cls': '', 'doc': first_sentence(doc_before(source, m.start())),
            'file': file, 'line': line_of(source, m.start()),
        })
    for m in RE_FN_EXPR.finditer(source):
        name = m.group(1)
        params = re.sub(r'\s+', ' ', (m.group(2) or m.group(3) or '').strip())
        key = (file, m.start(), name)
        if key in seen: continue
        seen.add(key)
        out.append({
            'name': name, 'kind': 'arrow/expr', 'params': params,
            'cls': '', 'doc': first_sentence(doc_before(source, m.start())),
            'file': file, 'line': line_of(source, m.start()),
        })
    # Method shorthand inside classes - only emit when we know the enclosing class.
    if classes:
        for m in RE_METHOD.finditer(source):
            name, params = m.group(1), re.sub(r'\s+', ' ', m.group(2).strip())
            # Skip control keywords
            if name in {'if','for','while','switch','catch','do','return','function','else','try'}:
                continue
            cls = cls_for(m.start())
            if not cls: continue
            key = (file, m.start(), name)
            if key in seen: continue
            seen.add(key)
            out.append({
                'name': name, 'kind': 'method', 'params': params,
                'cls': cls, 'doc': first_sentence(doc_before(source, m.start())),
                'file': file, 'line': line_of(source, m.start()),
            })
    return out


def walk_js(root: str) -> list[Path]:
    out = []
    for r in ROOTS:
        base = Path(root) / r
        if not base.exists(): continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [d for d in dirnames if d not in SKIPS]
            for f in filenames:
                if f.endswith(EXTS) and '.min.' not in f:
                    out.append(Path(dirpath) / f)
    return out


def render(records: list[dict]) -> str:
    by_file: dict[str, list[dict]] = defaultdict(list)
    for r in records:
        by_file[r['file']].append(r)
    out = ['# Heratio JavaScript function / method catalogue', '',
           'Auto-generated by `/opt/ai/km/build_functions_kb_js.py`. Closes #58 part B.', '',
           f'**Coverage:** {len(records)} functions/methods across {len(by_file)} files.', '']
    for file in sorted(by_file):
        out.append(f'# {file}')
        out.append('')
        for r in sorted(by_file[file], key=lambda x: (x['cls'], x['name'])):
            label = f"{r['cls']}::{r['name']}" if r['cls'] else r['name']
            out.append(f'## {label}')
            out.append('')
            out.append(f"**Kind:** `{r['kind']}`  ")
            out.append(f"**Signature:** `({r['params']})`  ")
            out.append(f"**File:** `{r['file']}:{r['line']}`  ")
            if r['doc']:
                out.append('')
                out.append(r['doc'])
            out.append('')
    return '\n'.join(out)


def main() -> int:
    files = walk_js(HERATIO)
    print(f"[build_functions_kb_js] {len(files)} JS/TS files", file=sys.stderr)
    records: list[dict] = []
    for path in files:
        try:
            records.extend(parse_js(path, path.read_text(encoding='utf-8', errors='replace')))
        except Exception as e:
            print(f"[build_functions_kb_js] WARN: {path}: {e}", file=sys.stderr)
    md = render(records)
    Path(OUT_PATH).write_text(md, encoding='utf-8')
    print(f"[build_functions_kb_js] {len(records)} symbols; wrote {OUT_PATH} ({len(md):,} bytes)", file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
