#!/usr/bin/env python3
"""
build_functions_kb_routes.py - HTTP route catalogue for KM. Closes part F
of #58.

Calls `php artisan route:list --json` so we get Laravel's authoritative
view of every routed URL (vs. trying to grep packages/*/routes/web.php
ourselves and miss group middleware, prefixes, route models, etc.).

Output: /opt/ai/km/auto_functions_kb_routes.md

@copyright  Johan Pieterse / Plain Sailing
@license    AGPL-3.0-or-later
"""

from __future__ import annotations
import json
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

HERATIO  = "/usr/share/nginx/heratio"
OUT_PATH = "/opt/ai/km/auto_functions_kb_routes.md"


def fetch_routes() -> list[dict]:
    proc = subprocess.run(
        ["php", "artisan", "route:list", "--json"],
        cwd=HERATIO, capture_output=True, text=True, timeout=120,
    )
    if proc.returncode != 0:
        print(f"[build_functions_kb_routes] artisan failed: {proc.stderr[:500]}", file=sys.stderr)
        return []
    try:
        return json.loads(proc.stdout)
    except json.JSONDecodeError as e:
        print(f"[build_functions_kb_routes] JSON parse failed: {e}", file=sys.stderr)
        return []


def render(routes: list[dict]) -> str:
    by_action: dict[str, list[dict]] = defaultdict(list)
    for r in routes:
        # Group by Controller class - lets queries like "what routes hit
        # AiController?" answer in one section.
        action = r.get('action', '') or 'Closure'
        cls = action.split('@')[0] if '@' in action else action
        by_action[cls].append(r)

    out = ['# Heratio HTTP route catalogue', '',
           'Auto-generated by `/opt/ai/km/build_functions_kb_routes.py` from',
           '`php artisan route:list --json`. Closes #58 part F.', '',
           f'**Coverage:** {len(routes)} routes across {len(by_action)} controllers/closures.', '']

    for cls in sorted(by_action):
        out.append(f'# {cls}')
        out.append('')
        for r in sorted(by_action[cls], key=lambda x: x.get('uri', '')):
            method = r.get('method', '')
            uri = r.get('uri', '')
            name = r.get('name') or ''
            mw = r.get('middleware', [])
            if isinstance(mw, str):
                mw = [mw]
            action = r.get('action', '') or 'Closure'
            out.append(f"## `{method}` `/{uri}`")
            out.append('')
            if name: out.append(f"**Name:** `{name}`  ")
            out.append(f"**Action:** `{action}`  ")
            if mw:   out.append(f"**Middleware:** " + ', '.join(f'`{m}`' for m in mw))
            out.append('')
    return '\n'.join(out)


def main() -> int:
    routes = fetch_routes()
    if not routes:
        return 1
    md = render(routes)
    Path(OUT_PATH).write_text(md, encoding='utf-8')
    print(f"[build_functions_kb_routes] {len(routes)} routes; wrote {OUT_PATH} ({len(md):,} bytes)", file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
