"""
ingest_heratio.py - Ingest Heratio documentation into Qdrant.

Reads all markdown docs from:
  - atom-extensions-catalog/docs/ (user guides, technical docs)
  - atom-ahg-plugins/*/docs/ and */README.md
  - atom-framework/docs/ and README.md
  - Root CLAUDE.md, MIGRATION.md etc.
  - extension.json descriptions from all plugins

Chunks and embeds into 'km_heratio' collection, separate from community Q&A.

Usage:
    python ingest_heratio.py
    python ingest_heratio.py --reset
"""

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path

from qdrant_client import QdrantClient
from qdrant_client.models import Distance, VectorParams, PointStruct
from sentence_transformers import SentenceTransformer

QDRANT_URL   = "http://localhost:6333"
COLLECTION   = "km_heratio"
VECTOR_SIZE  = 384
MODEL_NAME   = "all-MiniLM-L6-v2"
BATCH_SIZE   = 100

BASE = "/usr/share/nginx/archive"
HERATIO = "/usr/share/nginx/heratio"

# Documentation source directories
DOC_SOURCES = [
    # User guides and feature overviews
    (f"{BASE}/atom-extensions-catalog/docs", "user-guide"),
    (f"{BASE}/atom-extensions-catalog/docs/technical", "technical"),
    # Framework docs
    (f"{BASE}/atom-framework/docs", "framework"),
    (f"{BASE}/atom-framework/docs/search", "framework"),
    (f"{BASE}/atom-framework/docs/issues", "framework"),
    # Plugin docs
    (f"{BASE}/atom-ahg-plugins", "plugin"),
    # Heratio (Laravel port) - separate checkout, has its own docs tree
    (f"{HERATIO}/docs/user-manual", "heratio-user-manual"),
    (f"{HERATIO}/docs/install", "heratio-install"),
    (f"{HERATIO}/docs/getting-started", "heratio-getting-started"),
    (f"{HERATIO}/docs/developer", "heratio-developer"),
    (f"{HERATIO}/docs/technical", "heratio-technical"),
    (f"{HERATIO}/docs/operations", "heratio-operations"),
    (f"{HERATIO}/docs/reference", "heratio-reference"),
    (f"{HERATIO}/docs/adr", "heratio-adr"),
    # OpenRiC specification documents
    (f"{BASE}/openric-spec/spec", "openric-spec"),
    # Root docs for archive/* (also walks newly-cloned OpenRiC, openric-spec, SDK READMEs)
    (f"{BASE}", "overview"),
]

# Specific root files to include
ROOT_FILES = [
    # archive/CLAUDE.md intentionally excluded - describes the legacy "AtoM Heratio =
    # AtoM 2.10 + AHG Framework" framing; heratio repo README is current source of truth.
    (f"{BASE}/atom-framework/CLAUDE.md", "framework", "Framework Architecture"),
    (f"{BASE}/atom-framework/README.md", "framework", "Framework README"),
    (f"{BASE}/atom-ahg-plugins/README.md", "plugin", "Plugin System Overview"),
    (f"{HERATIO}/CLAUDE.md", "heratio", "Heratio Project Overview"),
    (f"{HERATIO}/README.md", "heratio", "Heratio README"),
    # Auto-generated structural KB (rebuilt by build_heratio_kb.py before each
    # ingest cycle - covers package catalogue, plugin catalogue, schema map,
    # capability map, service surface, design principles).
    ("/opt/ai/km/auto_heratio_kb.md", "heratio-auto", "Heratio Auto-KB"),
    # Multi-project knowledge base (rebuilt by build_projects_kb.py - covers
    # every theahg.co.za vhost, codebase, database, NAS path, backups, cron,
    # and systemd timer on this server).
    ("/opt/ai/km/auto_projects_kb.md", "projects-auto", "theahg.co.za Projects Auto-KB"),
    # Docker test stack reference - install / reset / inspect / caveats.
    # Lives outside docs/ tree so it's not picked up by the DOC_SOURCES walk.
    (f"{HERATIO}/docker/README.md", "heratio-docker", "Heratio Docker Stack Reference"),
    (f"{BASE}/atom-ahg-python/README.md", "sdk-python", "AtoM Python SDK"),
    (f"{BASE}/atom-client-js/README.md", "sdk-js", "AtoM JavaScript/TypeScript SDK"),
    (f"{BASE}/OpenRiC/README.md", "openric", "OpenRiC"),
    (f"{BASE}/openric-spec/README.md", "openric-spec", "OpenRiC Specification"),
    (f"{BASE}/openric-spec/index.md", "openric-spec", "OpenRiC Specification Index"),
    # #58 auto function/method/route catalogues - regenerated by
    # /opt/ai/km/build_functions_kb*.py (driven by km-build-functions.timer)
    # so the inotify watcher picks them up on the next debounce cycle.
    ("/opt/ai/km/auto_functions_kb.md",        "heratio-functions-php",   "Heratio PHP function catalogue"),
    ("/opt/ai/km/auto_functions_kb_js.md",     "heratio-functions-js",    "Heratio JavaScript catalogue"),
    ("/opt/ai/km/auto_functions_kb_blade.md",  "heratio-functions-blade", "Heratio Blade view catalogue"),
    ("/opt/ai/km/auto_functions_kb_py.md",     "heratio-functions-py",    "KM/operator Python catalogue"),
    ("/opt/ai/km/auto_functions_kb_routes.md", "heratio-routes",          "Heratio HTTP route catalogue"),
]

# Skip these paths
SKIP_PATTERNS = [
    "node_modules", "vendor", "venv", ".git", "cache",
    "DATABASE_ERD.md",  # 500KB, not useful for Q&A
    "FUNCTIONS.md",     # 82KB raw function list
    # Legacy "AtoM Heratio = AtoM 2.10 + AHG Framework" framing - contradicts the
    # current heratio repo (Laravel 12 rewrite). heratio repo docs are source of truth.
    "AtoM_Heratio_",
    # Other legacy plugin-framing user guides
    "research-training-manual-user-guide.md",
    "researcher-user-guide.md",
    "security-user-manual.md",
    "ahgResearchPlugin/docs/USER_GUIDE.md",
    "ahgResearchPlugin/docs/AtoM_Heratio_Research_Portal_Training_Manual",
    "samab/SAMAB_2026_AI_Collections_Steward.md",
    # Tender / RFB docs - not appropriate for public KM
    "/ontario/",
]


def should_skip(path: str) -> bool:
    return any(skip in path for skip in SKIP_PATTERNS)


# 2026-04-30 - credential redaction. After audit found the heratio MySQL root
# password, atom DB password, AHG AI API key and admin login retrievable via
# https://km.theahg.co.za/api/ask, every chunk is scrubbed of literal
# credentials / private IPs / SSH keys before it lands in Qdrant.
# 2026-05-07 (#49) - moved to shared /opt/ai/km/redact.py so every ingest
# script inherits the same floor. Pattern set lives in that module.
from redact import redact_secrets  # noqa: E402


def chunk_markdown(text: str, max_len: int = 600) -> list[dict]:
    """Split markdown by headings into semantic chunks."""
    text = redact_secrets(text)
    chunks = []
    # Split on headings
    sections = re.split(r'\n(#{1,4}\s+.+)\n', text)

    current_heading = ""
    current_text = ""

    for part in sections:
        part = part.strip()
        if not part:
            continue

        if re.match(r'^#{1,4}\s+', part):
            # Save previous chunk
            if current_text and len(current_text) > 30:
                chunks.append({
                    "heading": current_heading,
                    "text": current_text.strip(),
                })
            current_heading = part.lstrip('#').strip()
            current_text = ""
        else:
            current_text += "\n" + part

    # Last chunk
    if current_text and len(current_text) > 30:
        chunks.append({
            "heading": current_heading,
            "text": current_text.strip(),
        })

    # Split any oversized chunks
    final = []
    for chunk in chunks:
        text = chunk["text"]
        if len(text) <= max_len:
            final.append(chunk)
        else:
            # Split by paragraphs
            paragraphs = text.split("\n\n")
            current = ""
            for para in paragraphs:
                if len(current) + len(para) + 2 <= max_len:
                    current = (current + "\n\n" + para).strip()
                else:
                    if current:
                        final.append({"heading": chunk["heading"], "text": current})
                    current = para[:max_len] if len(para) > max_len else para
            if current:
                final.append({"heading": chunk["heading"], "text": current})

    return final


def extract_plugin_info(plugin_dir: str) -> list[dict]:
    """Extract info from extension.json files."""
    records = []
    ext_path = os.path.join(plugin_dir, "extension.json")
    if not os.path.exists(ext_path):
        return records

    try:
        data = json.loads(Path(ext_path).read_text())
        name = data.get("name", "")
        desc = data.get("description", "")
        version = data.get("version", "")
        features = data.get("features", {})
        category = data.get("category", "")

        if desc:
            text = f"Plugin: {name}\nVersion: {version}\nCategory: {category}\n\n{desc}"
            if features:
                text += "\n\nFeatures:\n"
                for k, v in features.items():
                    if isinstance(v, bool) and v:
                        text += f"- {k}\n"
                    elif isinstance(v, str):
                        text += f"- {k}: {v}\n"

            records.append({
                "heading": f"Plugin: {name}",
                "text": text,
                "source_file": ext_path,
                "category": "plugin",
            })
    except:
        pass

    return records


def collect_all_docs() -> list[dict]:
    """Collect all documentation chunks."""
    all_records = []

    # 1. Specific root files
    for filepath, category, title in ROOT_FILES:
        if not os.path.exists(filepath):
            continue
        text = Path(filepath).read_text(encoding="utf-8", errors="ignore")
        chunks = chunk_markdown(text)
        for chunk in chunks:
            all_records.append({
                "heading": chunk["heading"] or title,
                "text": chunk["text"],
                "source_file": filepath,
                "category": category,
            })
        print(f"  {filepath}: {len(chunks)} chunks")

    # 2. Documentation directories
    for doc_dir, category in DOC_SOURCES:
        if not os.path.isdir(doc_dir):
            continue

        for root, dirs, files in os.walk(doc_dir):
            if should_skip(root):
                continue

            for fname in files:
                if not fname.endswith(".md"):
                    continue

                filepath = os.path.join(root, fname)
                if should_skip(filepath):
                    continue

                try:
                    text = Path(filepath).read_text(encoding="utf-8", errors="ignore")
                except:
                    continue

                if len(text) < 50:
                    continue

                # Determine category from path
                doc_category = category
                if "technical" in filepath.lower():
                    doc_category = "technical"
                elif "user-guide" in fname.lower() or "user_guide" in fname.lower() or "user-manual" in fname.lower():
                    doc_category = "user-guide"
                elif "feature-overview" in fname.lower() or "feature_overview" in fname.lower():
                    doc_category = "feature-overview"

                chunks = chunk_markdown(text)
                for chunk in chunks:
                    # Build a title from filename if no heading
                    title = chunk["heading"]
                    if not title:
                        title = fname.replace(".md", "").replace("-", " ").replace("_", " ").title()

                    all_records.append({
                        "heading": title,
                        "text": chunk["text"],
                        "source_file": filepath,
                        "category": doc_category,
                    })

                if chunks:
                    print(f"  {filepath}: {len(chunks)} chunks")

    # 3. Extension.json from all plugins
    plugins_dir = f"{BASE}/atom-ahg-plugins"
    if os.path.isdir(plugins_dir):
        for pname in sorted(os.listdir(plugins_dir)):
            pdir = os.path.join(plugins_dir, pname)
            if os.path.isdir(pdir) and pname.startswith("ahg"):
                records = extract_plugin_info(pdir)
                all_records.extend(records)

    return all_records


def make_id(source_file: str, heading: str, text: str) -> str:
    """Content-addressed ID: same chunk → same ID across runs (idempotent upserts)."""
    raw = f"{source_file}|{heading}|{text}"
    return hashlib.md5(raw.encode()).hexdigest()


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--reset", action="store_true")
    args = ap.parse_args()

    # Refresh the auto-generated structural KBs first so the package /
    # plugin / schema sections are current with this run's MySQL state.
    import subprocess
    for script in ("/opt/ai/km/build_heratio_kb.py",
                   "/opt/ai/km/build_projects_kb.py"):
        try:
            subprocess.run(
                ["/opt/ai/km/venv/bin/python", script],
                check=True,
                timeout=120,
            )
        except Exception as e:
            print(f"[!] {script} regen failed (continuing with stale file): {e}")

    print("[1] Collecting Heratio documentation...")
    records = collect_all_docs()
    print(f"    Total: {len(records)} chunks\n")

    if not records:
        print("[!] No records found.")
        sys.exit(0)

    # Deduplicate by text
    seen = set()
    unique = []
    for r in records:
        key = r["text"][:200]
        if key not in seen:
            seen.add(key)
            unique.append(r)
    records = unique
    print(f"    After dedup: {len(records)} chunks\n")

    # Connect to Qdrant
    client = QdrantClient(url=QDRANT_URL)

    if args.reset:
        try:
            client.delete_collection(COLLECTION)
        except:
            pass

    collections = [c.name for c in client.get_collections().collections]
    if COLLECTION not in collections:
        print(f"[2] Creating collection '{COLLECTION}'...")
        client.create_collection(
            collection_name=COLLECTION,
            vectors_config=VectorParams(size=VECTOR_SIZE, distance=Distance.COSINE),
            on_disk_payload=True,
        )
    else:
        info = client.get_collection(COLLECTION)
        print(f"[2] Collection exists ({info.points_count} points)")

    print(f"[3] Loading model...")
    model = SentenceTransformer(MODEL_NAME)

    # For embedding, prepend heading as context
    print(f"[4] Embedding and upserting {len(records)} chunks...")
    for i in range(0, len(records), BATCH_SIZE):
        batch = records[i:i + BATCH_SIZE]
        texts = [f"{r['heading']}: {r['text']}" if r['heading'] else r['text'] for r in batch]
        embeddings = model.encode(texts, show_progress_bar=False)

        points = []
        for idx, (rec, emb) in enumerate(zip(batch, embeddings)):
            points.append(PointStruct(
                id=make_id(rec["source_file"], rec["heading"], rec["text"]),
                vector=emb.tolist(),
                payload={
                    "text":        rec["text"],
                    "heading":     rec["heading"],
                    "source_file": rec["source_file"],
                    "category":    rec["category"],
                    "source":      "heratio",
                },
            ))

        client.upsert(collection_name=COLLECTION, points=points)
        done = min(i + BATCH_SIZE, len(records))
        if done % 500 == 0 or done == len(records):
            print(f"    {done}/{len(records)}")

    info = client.get_collection(COLLECTION)
    print(f"\n[OK] {info.points_count} Heratio doc chunks indexed in '{COLLECTION}'")


if __name__ == "__main__":
    main()
