#!/usr/bin/env python3
import subprocess, json, time
from pathlib import Path

HERATIO = Path("/usr/share/nginx/heratio")
OUT = HERATIO / "audit_outputs"
REPO = "ArchiveHeritageGroup/heratio"

# Packages that need issues created (failed from last run + ⏳ status entries)
packages = [
    "ahg-metadata-export", "ahg-metadata-extraction", "ahg-mods-manage",
    "ahg-multi-tenant", "ahg-museum", "ahg-narssa", "ahg-naz", "ahg-nmmz",
    "ahg-oai", "ahg-pdf-tools", "ahg-portable-export", "ahg-preservation",
    "ahg-privacy", "ahg-provenance", "ahg-provenance-ai", "ahg-rad-manage",
    "ahg-records-manage", "ahg-reports", "ahg-repository-manage",
    "ahg-request-publish", "ahg-research", "ahg-researcher-manage",
    "ahg-rights", "ahg-rights-holder-manage", "ahg-scan", "ahg-search",
    "ahg-security-clearance", "ahg-semantic-search", "ahg-settings",
    "ahg-share-link", "ahg-static-page", "ahg-statistics", "ahg-storage-manage",
    "ahg-term-taxonomy", "ahg-theme-b5", "ahg-translation", "ahg-user-manage",
    "ahg-vendor", "ahg-version-control", "ahg-workflow"
]

# Load existing issue map
issue_map = json.loads((OUT / "gh_issue_map.json").read_text())

# Load existing issues created log
issues_created = json.loads((OUT / "gh_issues_created.json").read_text())

created = issues_created.get("created", [])
failed = issues_created.get("failed", [])

print(f"Need to create {len(packages)} issues...")

for i, pkg in enumerate(packages):
    # Generate body
    body = f"""## {pkg} — Incomplete scaffold

**Status:** Audit incomplete — scaffold step pending.

This package is part of the Heratio ecosystem audit (2025). Initial scaffolding (README.md + help stubs) has been added via local commit but the full implementation is pending.

### Missing items (audit checkpoint)
"""
    # Add missing items from full_audit_status or deep_audit
    missing_info = {
        "ahg-metadata-export": ["services", "readme"],
        "ahg-metadata-extraction": ["db", "readme"],
        "ahg-mods-manage": ["services", "db", "readme"],
        "ahg-multi-tenant": ["readme"],
        "ahg-museum": ["readme"],
        "ahg-narssa": ["controllers", "views", "readme"],
        "ahg-naz": ["services", "readme"],
        "ahg-nmmz": ["readme"],
        "ahg-oai": ["services", "views", "db", "readme"],
        "ahg-pdf-tools": ["db", "readme", "docs_help"],
        "ahg-portable-export": ["services", "readme"],
        "ahg-preservation": ["readme"],
        "ahg-privacy": ["readme"],
        "ahg-provenance": ["readme"],
        "ahg-provenance-ai": ["readme"],
        "ahg-rad-manage": ["services", "db", "readme"],
        "ahg-records-manage": ["readme"],
        "ahg-reports": ["readme"],
        "ahg-repository-manage": ["readme"],
        "ahg-request-publish": ["services", "readme", "docs_help"],
        "ahg-research": ["readme"],
        "ahg-researcher-manage": ["readme", "docs_help"],
        "ahg-rights": ["controllers", "services", "views", "routes", "readme"],
        "ahg-rights-holder-manage": ["readme"],
        "ahg-scan": ["readme"],
        "ahg-search": ["readme"],
        "ahg-security-clearance": ["readme"],
        "ahg-semantic-search": ["readme"],
        "ahg-settings": ["readme"],
        "ahg-share-link": ["readme"],
        "ahg-static-page": ["services", "readme"],
        "ahg-statistics": ["readme"],
        "ahg-storage-manage": ["readme"],
        "ahg-term-taxonomy": ["readme"],
        "ahg-theme-b5": ["controllers", "readme"],
        "ahg-translation": ["readme"],
        "ahg-user-manage": ["readme"],
        "ahg-vendor": ["readme"],
        "ahg-version-control": ["readme"],
        "ahg-workflow": ["readme"],
    }
    
    for item in missing_info.get(pkg, ["readme"]):
        body += f"- [ ] `{item}`\n"
    
    body += f"""
### References
- Source: `packages/{pkg}/`
- Help: `docs/help/{pkg.replace('ahg-','ahg-').lstrip('ahg-')}-user-guide.md`

---
> Generated by automated audit runner. Full implementation of missing items required by assignee.
"""

    # Write body to temp file
    body_file = OUT / f"_temp_issue_body_{pkg}.txt"
    body_file.write_text(body)
    
    title = f"audit: {pkg} — incomplete scaffold"
    
    cmd = [
        "gh", "issue", "create",
        "--repo", REPO,
        "--title", title,
        "--body-file", str(body_file),
        "--label", "audit"
    ]
    
    result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    body_file.unlink()
    
    if result.returncode == 0:
        url = result.stdout.strip()
        gh_num = url.split("/")[-1]
        created.append({"pkg": pkg, "url": url, "gh_num": int(gh_num)})
        issue_map[gh_num] = pkg
        print(f"  OK {pkg} -> #{gh_num}")
    else:
        err = result.stderr.strip()[:150]
        failed.append([pkg, err])
        print(f"  FAIL {pkg}: {err}")
    
    time.sleep(0.5)

# Save results
issues_created["created"] = created
issues_created["failed"] = failed
(OUT / "gh_issues_created.json").write_text(json.dumps(issues_created, indent=2))
(OUT / "gh_issue_map.json").write_text(json.dumps(issue_map, indent=2))

print(f"\nDONE: created={len(created)}, failed={len(failed)}")
for pkg, err in failed:
    print(f"  FAILED: {pkg}: {err}")