#!/usr/bin/env python3
"""
fix_all_audit_packages.py
=========================
Goes through all 103 packages from the Heratio audit. For each package with
missing items, updates the README.md stub with the correct GH issue number
(and for packages with only README missing, also writes the actual stub content).

Usage:
    python3 fix_all_audit_packages.py [--dry-run]
"""

import json, os, re, sys

# ── Config ────────────────────────────────────────────────────────────────────
PACKAGES_DIR = "/usr/share/nginx/heratio/packages"
AUDIT_JSON   = "/usr/share/nginx/heratio/audit_outputs/full_audit_111_raw.json"
STATUS_FILE  = "/usr/share/nginx/heratio/audit_outputs/full_audit_status.txt"
GH_MAP_JSON  = "/usr/share/nginx/heratio/audit_outputs/gh_issue_map.json"
LOG_FILE     = "/usr/share/nginx/heratio/audit_outputs/fix_log.txt"

SKIP_ISSUES = {144, 145}   # pre-existing, unrelated to audit

DRY_RUN = "--dry-run" in sys.argv

# ── Helpers ───────────────────────────────────────────────────────────────────

def read_json(path):
    with open(path) as f:
        return json.load(f)

def log(msg):
    print(msg)
    lines.append(msg)

def scan_dir(package, subdirs):
    """Return dict of found/missing for a package."""
    pkg_path = os.path.join(PACKAGES_DIR, package)
    return {sub: os.path.exists(os.path.join(pkg_path, sub)) for sub in subdirs}

def readme_content(package, missing, gh_number, check):
    """Build README stub for a package, using existing package structure."""
    short = package.replace("ahg-", "")   # e.g. "share-link"
    stub = f"""# {package}

> Auto-generated by Heratio audit (see [GH issue #{gh_number}](https://github.com/ArchiveHeritageGroup/heratio/issues/{gh_number})).
> Package status: **needs implementation** — {len(missing)} missing item(s).

## Quick facts

| Field | Value |
|-------|-------|
| Package | `{package}` |
| GH Issue | [#{gh_number}](https://github.com/ArchiveHeritageGroup/heratio/issues/{gh_number}) |
| Missing | {', '.join(missing)} |

## Source structure (current)

| Component | Status |
|-----------|--------|
"""

    subdirs = ["src/Controllers", "src/Services", "resources/views",
               "routes", "database", "src/Jobs", "src/Console", "src/Events",
               "src/Notifications", "tests", "src/Middleware"]

    found = scan_dir(package, subdirs)
    for sub in subdirs:
        label = sub.replace("src/", "").replace("resources/", "")
        stub += f"| {label} | {'✅ Present' if found[sub] else '❌ Missing'} |\n"

    stub += f"""
## Missing items checklist

"""
    for m in missing:
        stub += f"- [ ] **{m}**\n"

    stub += f"""
## Implementing

```bash
# 1. Navigate to package
cd packages/{package}

# 2. Check current state
ls -la
ls src/Controllers/ 2>/dev/null || echo "No controllers"
ls src/Services/     2>/dev/null || echo "No services"
ls resources/views/  2>/dev/null || echo "No views"
ls routes/           2>/dev/null || echo "No routes"
ls database/install.sql 2>/dev/null || echo "No install.sql"

# 3. Verify GH issue
gh issue view {gh_number} --repo ArchiveHeritageGroup/heratio
```

## Closing the issue

Once all missing items above are addressed, run the verification script:

```bash
python audit_checker.py {package}
```

If the audit returns no missing items, add a comment to [GH issue #{gh_number}](https://github.com/ArchiveHeritageGroup/heratio/issues/{gh_number}) confirming implementation is complete, then close the issue.
"""

    return stub

# ── Load data ─────────────────────────────────────────────────────────────────

audit_data = read_json(AUDIT_JSON)
gh_map     = read_json(GH_MAP_JSON)

# ── Build package → GH# mapping from status file + map ───────────────────────
pkg_to_gh = {}
for line in open(STATUS_FILE):
    line = line.strip()
    if not line or line.startswith("#") or ":" not in line:
        continue
    # Format: "✅ ahg-foo: missing=[...] | GH #NNN"  or "⏳ ahg-bar: ... | GH #TBD"
    m = re.match(r"[✅⏳]\s+(\S+):\s+.*?\| GH #(\S+)", line)
    if m:
        pkg, gh = m.group(1), m.group(2)
        pkg_to_gh[pkg] = gh if gh != "TBD" else None

# ── Process ───────────────────────────────────────────────────────────────────

lines = []
actions = 0

for pkg_data in audit_data:
    package = pkg_data["package"]
    missing = pkg_data.get("missing", [])
    check   = pkg_data.get("check_details", {})

    if not missing:
        log(f"[SKIP] {package} — fully implemented")
        continue

    gh_raw = pkg_to_gh.get(package)
    if gh_raw is None:
        log(f"[TBD]  {package} — no GH issue number yet ({missing})")
        continue

    try:
        gh_num = int(gh_raw)
    except ValueError:
        log(f"[SKIP] {package} — invalid GH# '{gh_raw}'")
        continue

    if gh_num in SKIP_ISSUES:
        log(f"[SKIP] {package} — GH #{gh_num} in skip list")
        continue

    readme_path = os.path.join(PACKAGES_DIR, package, "README.md")
    needs_write = False

    # Check if README exists and is a stub (has "#TBD" or is very short <30 chars)
    if os.path.exists(readme_path):
        content = open(readme_path).read()
        if "#TBD" in content or len(content.strip()) < 30:
            needs_write = True
    else:
        needs_write = True

    if DRY_RUN:
        status = "DRY" if needs_write else "OK  "
        log(f"[{status}] {package} — #{gh_num} ({len(missing)} missing)")
    elif needs_write:
        new_content = readme_content(package, missing, gh_num, check)
        with open(readme_path, "w") as f:
            f.write(new_content)
        log(f"[WROTE] {package} — README.md updated, GH #{gh_num}")
        actions += 1
    else:
        log(f"[OK  ] {package} — README.md already current, GH #{gh_num}")

log(f"\n{'Dry-run' if DRY_RUN else 'Done'}. {actions} files written.")

with open(LOG_FILE, "w") as f:
    f.write("\n".join(lines))

print(f"\nLog: {LOG_FILE}")