<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Research Notes Export</title>
    <style>
        body { font-family: 'Georgia', serif; margin: 40px; color: #333; line-height: 1.6; }
        h1 { font-size: 1.6rem; border-bottom: 2px solid #333; padding-bottom: 8px; }
        .note { margin-bottom: 20px; padding: 15px; border: 1px solid #ddd; border-radius: 4px; page-break-inside: avoid; }
        .note-title { font-weight: bold; font-size: 1.1rem; margin-bottom: 5px; }
        .note-meta { color: #888; font-size: 0.8rem; margin-bottom: 8px; }
        .note-content { font-size: 0.95rem; }
        .note-tags { margin-top: 8px; }
        .tag { display: inline-block; background: #e9ecef; padding: 1px 8px; border-radius: 10px; font-size: 0.75rem; margin-right: 4px; }
        .footer { margin-top: 30px; border-top: 1px solid #ccc; padding-top: 10px; font-size: 0.8rem; color: #888; text-align: center; }
        .no-print { margin-bottom: 20px; }
        @media print { .no-print { display: none !important; } }
    </style>
</head>
<body>
    <div class="no-print" style="background:#f8f9fa; padding:12px; border-radius:8px; display:flex; justify-content:space-between; align-items:center;">
        <a href="{{ route('research.annotations') }}">&larr; Back to Notes</a>
        <button onclick="window.print()" style="padding:6px 14px; background:#dc3545; color:#fff; border:none; border-radius:4px; cursor:pointer;">{{ __('Print / Save as PDF') }}</button>
    </div>

    <h1>{{ __('Research Notes') }}</h1>
    <p style="color:#666; font-size:0.9rem;">
        Author: {{ e(($researcher->first_name ?? '') . ' ' . ($researcher->last_name ?? '')) }}<br>
        Exported: {{ date('F j, Y') }} &middot; {{ $notes->count() }} note(s)
    </p>

    @foreach($notes as $n)
    <div class="note">
        <div class="note-title">{{ e($n->title ?: 'Untitled Note') }}</div>
        <div class="note-meta">
            {{ date('M j, Y H:i', strtotime($n->created_at)) }}
            @if($n->visibility ?? null) &middot; {{ ucfirst($n->visibility) }} @endif
        </div>
        <div class="note-content">
            @if(($n->content_format ?? 'text') === 'html')
                {!! $n->content !!}
            @else
                {!! nl2br(e($n->content ?? '')) !!}
            @endif
        </div>
        @if($n->tags ?? null)
        <div class="note-tags">
            @foreach(array_map('trim', explode(',', $n->tags)) as $t)
                @if($t)<span class="tag">{{ e($t) }}</span>@endif
            @endforeach
        </div>
        @endif
    </div>
    @endforeach

    <div class="footer">Generated by Heratio &mdash; {{ date('F j, Y \a\t H:i') }}</div>
</body>
</html>
