<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ e($report->title) }}</title>
    <style>
        body { font-family: 'Georgia', 'Times New Roman', serif; margin: 40px; color: #333; line-height: 1.6; }
        h1 { font-size: 1.8rem; border-bottom: 3px double #333; padding-bottom: 10px; }
        h2 { font-size: 1.3rem; margin-top: 30px; border-bottom: 1px solid #999; padding-bottom: 5px; color: #555; }
        .meta { color: #666; font-size: 0.9rem; margin-bottom: 30px; }
        .section { margin-bottom: 25px; page-break-inside: avoid; }
        .section-title { font-weight: bold; font-size: 1.1rem; color: #444; margin-bottom: 8px; border-left: 4px solid #0d6efd; padding-left: 10px; }
        .section-content { font-size: 0.95rem; padding-left: 14px; }
        .section-type { color: #888; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 1px; }
        .footer { margin-top: 40px; padding-top: 15px; border-top: 1px solid #ccc; font-size: 0.8rem; color: #888; text-align: center; }
        .status { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 0.8rem; font-weight: bold; }
        .status-draft { background: #e9ecef; color: #495057; }
        .status-in_progress { background: #cfe2ff; color: #084298; }
        .status-review { background: #fff3cd; color: #664d03; }
        .status-completed { background: #d1e7dd; color: #0f5132; }
        .no-print { margin-bottom: 20px; }
        @media print {
            .no-print { display: none !important; }
            body { margin: 20px; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="background:#f8f9fa; padding:15px; border-radius:8px; display:flex; justify-content:space-between; align-items:center;">
        <a href="{{ route('research.viewReport', $report->id) }}" style="text-decoration:none;">&larr; Back to Report</a>
        <button onclick="window.print()" style="padding:8px 16px; background:#dc3545; color:#fff; border:none; border-radius:4px; cursor:pointer;">
            {{ __('Print / Save as PDF') }}
        </button>
    </div>

    <h1>{{ e($report->title) }}</h1>
    <div class="meta">
        <span class="status status-{{ $report->status ?? 'draft' }}">{{ ucwords(str_replace('_', ' ', $report->status ?? 'draft')) }}</span>
        @if($report->template_type ?? null)
            &middot; {{ ucwords(str_replace('_', ' ', $report->template_type)) }}
        @endif
        <br>
        @if($report->description ?? null)
            {{ e($report->description) }}<br>
        @endif
        Author: {{ e(($researcher->first_name ?? '') . ' ' . ($researcher->last_name ?? '')) }}<br>
        Date: {{ date('F j, Y') }}
    </div>

    @if(!empty($report->sections) && count($report->sections) > 3)
    <h2>{{ __('Table of Contents') }}</h2>
    <ol style="font-size:0.9rem;">
        @foreach($report->sections as $s)
            <li><a href="#section-{{ $s->id }}" style="text-decoration:none; color:#333;">{{ e($s->title ?: ucfirst($s->section_type ?? 'Section')) }}</a></li>
        @endforeach
    </ol>
    @endif

    @if(!empty($report->sections))
        @foreach($report->sections as $s)
        <div class="section" id="section-{{ $s->id }}">
            <div class="section-title">{{ e($s->title ?: ucfirst($s->section_type ?? 'Section')) }}</div>
            @if($s->section_type ?? null)
                <div class="section-type">{{ $s->section_type }}</div>
            @endif
            <div class="section-content">
                @if($s->content ?? null)
                    {!! $s->content !!}
                @else
                    <p style="color:#999; font-style:italic;">No content yet.</p>
                @endif
            </div>
        </div>
        @endforeach
    @else
        <p style="color:#999;">This report has no sections.</p>
    @endif

    <div class="footer">
        Generated by Heratio &mdash; {{ date('F j, Y \a\t H:i') }}
    </div>
</body>
</html>
