@extends('theme::layouts.1col')
@section('title', 'Integrity - Certificate ' . $cert->certificate_number)
@section('body-class', 'admin integrity certificates view')
@section('title-block')
  <div class="multiline-header d-flex align-items-center mb-3">
    <i class="fas fa-3x fa-shield-alt me-3" aria-hidden="true"></i>
    <div class="d-flex flex-column"><h1 class="mb-0">{{ __('Destruction Certificate') }}</h1><span class="small text-muted">{{ $cert->certificate_number }}</span></div>
  </div>
@endsection
@section('content')

@if(session('success'))
<div class="alert alert-success alert-dismissible fade show d-print-none">{{ session('success') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>
@endif

<div class="card">
  <div class="card-header d-flex justify-content-between align-items-center" style="background-color:var(--ahg-card-header-bg, #005837);color:var(--ahg-card-header-text, #fff);">
    <h5 class="mb-0">{{ __('Certificate of Destruction') }}</h5>
    <button class="btn btn-sm btn-light d-print-none" onclick="window.print()"><i class="fas fa-print me-1"></i>Print</button>
  </div>
  <div class="card-body">
    <div class="text-center mb-4">
      <h3>{{ __('Certificate of Destruction') }}</h3>
      <p class="text-muted fs-5"><code>{{ $cert->certificate_number }}</code></p>
    </div>

    <table class="table table-bordered">
      <tbody>
        <tr><td style="width:200px;background:#f5f5f5;"><strong>Certificate Number</strong></td><td><code>{{ $cert->certificate_number }}</code></td></tr>
        <tr><td style="background:#f5f5f5;"><strong>Information Object</strong></td><td><a href="{{ url('/informationobject/show/' . $cert->information_object_id) }}">{{ $cert->io_title ?? 'Unknown' }}</a> (ID: {{ $cert->information_object_id }})</td></tr>
        <tr><td style="background:#f5f5f5;"><strong>Repository</strong></td><td>{{ $cert->repository_name ?? '-' }}</td></tr>
        <tr><td style="background:#f5f5f5;"><strong>Destruction Date</strong></td><td>{{ $cert->destruction_date }}</td></tr>
        <tr><td style="background:#f5f5f5;"><strong>Method of Destruction</strong></td><td>{{ ucfirst(str_replace('_', ' ', $cert->destruction_method)) }}</td></tr>
        <tr><td style="background:#f5f5f5;"><strong>Authorized By</strong></td><td>{{ $cert->authorized_by }}</td></tr>
        @if($cert->witness)
        <tr><td style="background:#f5f5f5;"><strong>Witness</strong></td><td>{{ $cert->witness }}</td></tr>
        @endif
        @if($cert->content_hash)
        <tr><td style="background:#f5f5f5;"><strong>Content Hash</strong></td><td><code class="small" style="word-break:break-all;">{{ $cert->content_hash }}</code></td></tr>
        @endif
        @if($cert->disposition_queue_id)
        <tr><td style="background:#f5f5f5;"><strong>Disposition Queue</strong></td><td>#{{ $cert->disposition_queue_id }}</td></tr>
        @endif
        <tr><td style="background:#f5f5f5;"><strong>Created</strong></td><td>{{ $cert->created_at }}</td></tr>
      </tbody>
    </table>

    <p class="mt-4">This certificate confirms that the above-described records have been destroyed in accordance with the applicable retention policy and authorization procedures.</p>

    <div class="row mt-5 d-print-block">
      <div class="col-6 d-inline-block" style="width:45%;">
        <div class="border-top border-dark pt-2 text-center">Authorized By</div>
      </div>
      <div class="col-6 d-inline-block" style="width:45%;margin-left:10%;">
        <div class="border-top border-dark pt-2 text-center">Witness</div>
      </div>
    </div>

    <p class="text-center text-muted small mt-4">Generated by Heratio Records Management System</p>
  </div>
</div>

<div class="mt-3 d-print-none">
  <a href="{{ route('integrity.certificates') }}" class="btn atom-btn-white"><i class="fas fa-arrow-left me-1"></i>Back to Certificates</a>
</div>
@endsection
