<?php

use Illuminate\Support\Facades\Route;

Route::prefix('admin/marketplace')->middleware(['web', 'auth'])->group(function () {
    Route::get('/admin-categories', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminCategories'])->name('ahgmarketplace.admin-categories');
    Route::get('/admin-currencies', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminCurrencies'])->name('ahgmarketplace.admin-currencies');
    Route::get('/admin-dashboard', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminDashboard'])->name('ahgmarketplace.admin-dashboard');
    Route::get('/admin-listing-review', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminListingReview'])->name('ahgmarketplace.admin-listing-review');
    Route::get('/admin-listings', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminListings'])->name('ahgmarketplace.admin-listings');
    Route::get('/admin-payouts', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminPayouts'])->name('ahgmarketplace.admin-payouts');
    Route::get('/admin-reports', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminReports'])->name('ahgmarketplace.admin-reports');
    Route::get('/admin-reviews', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminReviews'])->name('ahgmarketplace.admin-reviews');
    Route::get('/admin-seller-verify', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminSellerVerify'])->name('ahgmarketplace.admin-seller-verify');
    Route::get('/admin-sellers', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminSellers'])->name('ahgmarketplace.admin-sellers');
    Route::get('/admin-settings', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminSettings'])->name('ahgmarketplace.admin-settings');
    Route::get('/admin-transactions', [\AhgMarketplace\Controllers\MarketplaceController::class, 'adminTransactions'])->name('ahgmarketplace.admin-transactions');
    Route::get('/auction-browse', [\AhgMarketplace\Controllers\MarketplaceController::class, 'auctionBrowse'])->name('ahgmarketplace.auction-browse');
    Route::get('/bid-form', [\AhgMarketplace\Controllers\MarketplaceController::class, 'bidForm'])->name('ahgmarketplace.bid-form');
    Route::get('/browse', [\AhgMarketplace\Controllers\MarketplaceController::class, 'browse'])->name('ahgmarketplace.browse');
    Route::get('/category', [\AhgMarketplace\Controllers\MarketplaceController::class, 'category'])->name('ahgmarketplace.category');
    Route::get('/collection', [\AhgMarketplace\Controllers\MarketplaceController::class, 'collection'])->name('ahgmarketplace.collection');
    Route::get('/dashboard', [\AhgMarketplace\Controllers\MarketplaceController::class, 'dashboard'])->name('ahgmarketplace.dashboard');
    Route::get('/enquiry-form', [\AhgMarketplace\Controllers\MarketplaceController::class, 'enquiryForm'])->name('ahgmarketplace.enquiry-form');
    Route::get('/featured', [\AhgMarketplace\Controllers\MarketplaceController::class, 'featured'])->name('ahgmarketplace.featured');
    Route::get('/listing', [\AhgMarketplace\Controllers\MarketplaceController::class, 'listing'])->name('ahgmarketplace.listing');
    Route::get('/my-bids', [\AhgMarketplace\Controllers\MarketplaceController::class, 'myBids'])->name('ahgmarketplace.my-bids');
    Route::get('/my-following', [\AhgMarketplace\Controllers\MarketplaceController::class, 'myFollowing'])->name('ahgmarketplace.my-following');
    Route::get('/my-offers', [\AhgMarketplace\Controllers\MarketplaceController::class, 'myOffers'])->name('ahgmarketplace.my-offers');
    Route::get('/my-purchases', [\AhgMarketplace\Controllers\MarketplaceController::class, 'myPurchases'])->name('ahgmarketplace.my-purchases');
    Route::get('/offer-form', [\AhgMarketplace\Controllers\MarketplaceController::class, 'offerForm'])->name('ahgmarketplace.offer-form');
    Route::get('/review-form', [\AhgMarketplace\Controllers\MarketplaceController::class, 'reviewForm'])->name('ahgmarketplace.review-form');
    Route::get('/search', [\AhgMarketplace\Controllers\MarketplaceController::class, 'search'])->name('ahgmarketplace.search');
    Route::get('/sector', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sector'])->name('ahgmarketplace.sector');
    Route::get('/seller-analytics', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerAnalytics'])->name('ahgmarketplace.seller-analytics');
    Route::get('/seller-collection-create', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerCollectionCreate'])->name('ahgmarketplace.seller-collection-create');
    Route::get('/seller-collections', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerCollections'])->name('ahgmarketplace.seller-collections');
    Route::get('/seller-enquiries', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerEnquiries'])->name('ahgmarketplace.seller-enquiries');
    Route::get('/seller-listing-create', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerListingCreate'])->name('ahgmarketplace.seller-listing-create');
    Route::get('/seller-listing-edit', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerListingEdit'])->name('ahgmarketplace.seller-listing-edit');
    Route::get('/seller-listing-images', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerListingImages'])->name('ahgmarketplace.seller-listing-images');
    Route::get('/seller-listings', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerListings'])->name('ahgmarketplace.seller-listings');
    Route::get('/seller-offer-respond', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerOfferRespond'])->name('ahgmarketplace.seller-offer-respond');
    Route::get('/seller-offers', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerOffers'])->name('ahgmarketplace.seller-offers');
    Route::get('/seller-payouts', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerPayouts'])->name('ahgmarketplace.seller-payouts');
    Route::get('/seller-profile', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerProfile'])->name('ahgmarketplace.seller-profile');
    Route::get('/seller-register', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerRegister'])->name('ahgmarketplace.seller-register');
    Route::get('/seller-reviews', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerReviews'])->name('ahgmarketplace.seller-reviews');
    Route::get('/seller', [\AhgMarketplace\Controllers\MarketplaceController::class, 'seller'])->name('ahgmarketplace.seller');
    Route::get('/seller-transaction-detail', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerTransactionDetail'])->name('ahgmarketplace.seller-transaction-detail');
    Route::get('/seller-transactions', [\AhgMarketplace\Controllers\MarketplaceController::class, 'sellerTransactions'])->name('ahgmarketplace.seller-transactions');
});
