<?php

/**
 * InferenceSigner - Service for Heratio
 *
 * Copyright (C) 2026 Johan Pieterse
 * Plain Sailing Information Systems
 * Email: johan@plainsailingisystems.co.za
 *
 * This file is part of Heratio.
 *
 * Heratio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Heratio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with Heratio. If not, see <https://www.gnu.org/licenses/>.
 */

namespace AhgProvenanceAi\Services;

/**
 * Ed25519 signing of AI inference manifests (heratio#136).
 *
 * The keypair is operator-managed: generated by `ahg:provenance-ai:keygen`
 * into a gitignored directory under storage/ (storage/app/ai-signing by
 * default). The private key never enters the database or git - only the
 * detached signature and a short signer_key_id reference are persisted on
 * the ahg_ai_inference row.
 *
 * Signing is opt-in: until the keypair exists, sign() returns null and
 * inference rows are simply written unsigned - record() never fails because
 * signing is unconfigured.
 */
class InferenceSigner
{
    private string $keyDir;

    /** @param string|null $keyDir override the key directory (tests pass a temp dir). */
    public function __construct(?string $keyDir = null)
    {
        $this->keyDir = $keyDir ?? storage_path('app/ai-signing');
    }

    private function privatePath(): string { return $this->keyDir . '/ed25519.private'; }
    private function publicPath(): string  { return $this->keyDir . '/ed25519.public'; }
    private function keyIdPath(): string   { return $this->keyDir . '/key_id'; }

    /**
     * Generate the Ed25519 keypair. Refuses to overwrite an existing key
     * unless $force is set. Returns the signer_key_id.
     */
    public function generateKeypair(bool $force = false): string
    {
        if (!is_dir($this->keyDir) && !@mkdir($this->keyDir, 0700, true) && !is_dir($this->keyDir)) {
            throw new \RuntimeException('Could not create key directory: ' . $this->keyDir);
        }
        if (!$force && is_file($this->privatePath())) {
            throw new \RuntimeException(
                'A signing keypair already exists at ' . $this->keyDir . ' - pass --force to replace it.'
            );
        }

        $keypair = sodium_crypto_sign_keypair();
        $secret  = sodium_crypto_sign_secretkey($keypair);
        $public  = sodium_crypto_sign_publickey($keypair);
        $keyId   = $this->deriveKeyId($public);

        file_put_contents($this->privatePath(), base64_encode($secret));
        @chmod($this->privatePath(), 0600);
        file_put_contents($this->publicPath(), base64_encode($public));
        @chmod($this->publicPath(), 0640);
        file_put_contents($this->keyIdPath(), $keyId);

        sodium_memzero($secret);
        return $keyId;
    }

    /** True once a usable private key is present. */
    public function isEnabled(): bool
    {
        return is_file($this->privatePath());
    }

    /** The signer_key_id (e.g. "ed25519:1a2b3c4d5e6f7081"), or null if no key. */
    public function keyId(): ?string
    {
        return is_file($this->keyIdPath()) ? trim((string) file_get_contents($this->keyIdPath())) : null;
    }

    /** Raw (decoded) public key bytes, or null if no key. */
    public function publicKey(): ?string
    {
        if (!is_file($this->publicPath())) {
            return null;
        }
        $k = base64_decode(trim((string) file_get_contents($this->publicPath())), true);
        return $k === false ? null : $k;
    }

    /**
     * Sign a manifest. Returns a base64 detached Ed25519 signature, or null
     * when signing is not configured (no keypair) - the caller treats null
     * as "unsigned" rather than an error.
     */
    public function sign(array $manifest): ?string
    {
        if (!$this->isEnabled()) {
            return null;
        }
        $secret = base64_decode(trim((string) file_get_contents($this->privatePath())), true);
        if ($secret === false) {
            return null;
        }
        $signature = sodium_crypto_sign_detached($this->canonicalize($manifest), $secret);
        sodium_memzero($secret);

        return base64_encode($signature);
    }

    /**
     * Verify a base64 detached signature over a manifest against a raw
     * Ed25519 public key.
     */
    public function verify(string $signatureB64, array $manifest, string $publicKey): bool
    {
        $signature = base64_decode($signatureB64, true);
        if ($signature === false || strlen($signature) !== SODIUM_CRYPTO_SIGN_BYTES) {
            return false;
        }

        return sodium_crypto_sign_verify_detached($signature, $this->canonicalize($manifest), $publicKey);
    }

    /**
     * Deterministic canonical form of a manifest: recursively key-sorted,
     * compact JSON. Signer and verifier MUST agree on this byte string, so
     * key order and escaping are fixed here and nowhere else.
     */
    public function canonicalize(array $manifest): string
    {
        $sortRecursive = function (&$node) use (&$sortRecursive) {
            if (is_array($node)) {
                ksort($node);
                foreach ($node as &$child) {
                    if (is_array($child)) {
                        $sortRecursive($child);
                    }
                }
            }
        };
        $sortRecursive($manifest);

        return (string) json_encode($manifest, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
    }

    /** A short, stable reference derived from the public key. */
    private function deriveKeyId(string $publicKey): string
    {
        return 'ed25519:' . substr(hash('sha256', $publicKey), 0, 16);
    }
}
