<?php

/**
 * ahg:library-email-usage-reports
 *
 * Scheduled COUNTER R5 report email delivery (issue #766).
 *
 * For each recipient configured in ahg_settings.counter_email_recipients,
 * generate the configured report set for the previous calendar period,
 * attach as JSON + TSV, and email via the Mail facade.
 *
 * Settings (all in ahg_settings):
 *   counter_email_enabled         bool        master kill-switch (default false)
 *   counter_email_recipients      csv string  comma-separated email addresses
 *   counter_email_reports         csv string  comma-separated report IDs (PR,TR,DR,TR_J1,TR_J3,IR)
 *                                            default: TR,DR,PR
 *   counter_email_period          string      'monthly' (default) | 'quarterly' | 'yearly'
 *   counter_email_from_name       string      RFC 5322 'From' display name
 *
 * Scheduler runs this command monthly (1st of each month at 04:00 SAST,
 * after the KBART + circulation batches). The command computes the prior
 * period's date range itself based on `counter_email_period`.
 *
 * Issue: heratio#766
 *
 * Copyright (C) 2026 Johan Pieterse - Plain Sailing Information Systems - AGPL-3.0
 */

namespace AhgLibrary\Console\Commands;

use AhgLibrary\Services\LibraryUsageService;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Schema;
use Throwable;

class EmailUsageReportsCommand extends Command
{
    protected $signature = 'ahg:library-email-usage-reports
        {--dry-run : Build the reports but do not send the email}
        {--force   : Bypass the counter_email_enabled kill-switch (still requires recipients)}';

    protected $description = 'Email the prior period\'s COUNTER R5 usage reports to the configured recipients.';

    public function handle(LibraryUsageService $usage): int
    {
        $cfg = $this->loadConfig();

        if (!$cfg['enabled'] && !$this->option('force')) {
            $this->info('counter_email_enabled is off - skipping. Use --force to override for a one-off send.');
            return self::SUCCESS;
        }
        if (empty($cfg['recipients'])) {
            $this->warn('No recipients configured. Set ahg_settings.counter_email_recipients (comma-separated).');
            return self::SUCCESS;
        }

        [$beginDate, $endDate, $periodLabel] = $this->resolvePeriod($cfg['period']);
        $this->info("Building {$periodLabel} reports for {$beginDate} -> {$endDate} ...");

        $reportIds = array_filter(array_map('trim', explode(',', strtoupper($cfg['reports']))));
        if (empty($reportIds)) $reportIds = ['TR', 'DR', 'PR'];

        $attachments = [];
        foreach ($reportIds as $reportId) {
            try {
                $report = $usage->buildCounterReport($reportId, $beginDate, $endDate);
                $jsonName = sprintf('COUNTER_%s_%s_%s.json', $reportId, $beginDate, $endDate);
                $tsvName  = sprintf('COUNTER_%s_%s_%s.tsv',  $reportId, $beginDate, $endDate);
                $attachments[] = [
                    'name' => $jsonName,
                    'mime' => 'application/json',
                    'data' => json_encode($report, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE),
                ];
                $attachments[] = [
                    'name' => $tsvName,
                    'mime' => 'text/tab-separated-values',
                    'data' => $usage->getReportCsv($reportId, $beginDate, $endDate),
                ];
                $this->line("  built {$reportId} (" . count($report['Report_Items'] ?? []) . ' rows)');
            } catch (Throwable $e) {
                $this->warn("  {$reportId} build failed: " . $e->getMessage());
            }
        }

        if (empty($attachments)) {
            $this->error('No reports built - nothing to send.');
            return self::FAILURE;
        }

        $subject = sprintf('[Heratio COUNTER R5] %s usage reports (%s)', ucfirst($cfg['period']), $beginDate);
        $body = sprintf(
            "Attached are the COUNTER R5 reports for %s to %s.\n\nReport IDs: %s\nGenerated by Heratio (%s) on %s.\n",
            $beginDate, $endDate, implode(', ', $reportIds),
            (string) (config('app.url') ?: 'heratio'),
            now()->toIso8601String()
        );

        if ($this->option('dry-run')) {
            $this->info('--dry-run: skipping send. ' . count($attachments) . ' attachment(s) would be sent to: ' . implode(', ', $cfg['recipients']));
            $this->logSend($cfg['recipients'], $reportIds, $beginDate, $endDate, 'dry_run', null);
            return self::SUCCESS;
        }

        try {
            $fromName = $cfg['from_name'];
            Mail::raw($body, function ($m) use ($cfg, $subject, $attachments, $fromName) {
                $m->to($cfg['recipients']);
                $m->subject($subject);
                if ($fromName) {
                    $fromAddress = config('mail.from.address');
                    if ($fromAddress) $m->from($fromAddress, $fromName);
                }
                foreach ($attachments as $a) {
                    $m->attachData($a['data'], $a['name'], ['mime' => $a['mime']]);
                }
            });
            $this->info('Sent to: ' . implode(', ', $cfg['recipients']));
            $this->logSend($cfg['recipients'], $reportIds, $beginDate, $endDate, 'sent', null);
            return self::SUCCESS;

        } catch (Throwable $e) {
            $this->error('Send failed: ' . $e->getMessage());
            $this->logSend($cfg['recipients'], $reportIds, $beginDate, $endDate, 'failed', $e->getMessage());
            return self::FAILURE;
        }
    }

    /**
     * @return array{enabled:bool, recipients:array<string>, reports:string, period:string, from_name:?string}
     */
    private function loadConfig(): array
    {
        $get = function (string $key, $default = null) {
            try {
                return \AhgCore\Services\AhgSettingsService::get($key, $default);
            } catch (Throwable) {
                return $default;
            }
        };
        $recipientsRaw = (string) $get('counter_email_recipients', '');
        $recipients = array_filter(array_map('trim', explode(',', $recipientsRaw)), fn ($e) => filter_var($e, FILTER_VALIDATE_EMAIL));
        return [
            'enabled'    => (bool) $get('counter_email_enabled', false),
            'recipients' => array_values($recipients),
            'reports'    => (string) ($get('counter_email_reports', 'TR,DR,PR') ?: 'TR,DR,PR'),
            'period'     => (string) ($get('counter_email_period', 'monthly') ?: 'monthly'),
            'from_name'  => $get('counter_email_from_name', null),
        ];
    }

    /**
     * @return array{0:string, 1:string, 2:string} [beginDate, endDate, periodLabel]
     */
    private function resolvePeriod(string $period): array
    {
        return match (strtolower($period)) {
            'yearly'    => [now()->subYear()->startOfYear()->toDateString(),    now()->subYear()->endOfYear()->toDateString(),    'yearly'],
            'quarterly' => [now()->subQuarter()->startOfQuarter()->toDateString(), now()->subQuarter()->endOfQuarter()->toDateString(), 'quarterly'],
            default     => [now()->subMonthNoOverflow()->startOfMonth()->toDateString(), now()->subMonthNoOverflow()->endOfMonth()->toDateString(), 'monthly'],
        };
    }

    /**
     * Write a row to library_usage_email_log (best-effort - never throws).
     */
    private function logSend(array $recipients, array $reportIds, string $beginDate, string $endDate, string $status, ?string $error): void
    {
        try {
            if (!Schema::hasTable('library_usage_email_log')) {
                DB::statement("
                    CREATE TABLE IF NOT EXISTS library_usage_email_log (
                        id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                        recipients TEXT NOT NULL,
                        report_ids VARCHAR(120) NOT NULL,
                        begin_date DATE NOT NULL,
                        end_date DATE NOT NULL,
                        status VARCHAR(16) NOT NULL,
                        error TEXT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        INDEX ix_status (status),
                        INDEX ix_created (created_at)
                    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
                ");
            }
            DB::table('library_usage_email_log')->insert([
                'recipients' => implode(',', $recipients),
                'report_ids' => implode(',', $reportIds),
                'begin_date' => $beginDate,
                'end_date'   => $endDate,
                'status'     => $status,
                'error'      => $error,
                'created_at' => now(),
            ]);
        } catch (Throwable) {
            // never let logging break the command
        }
    }
}
