<?php

/**
 * Arabic labels for the standard taxonomy terms that ship with every install:
 * levels of description, event types, note types, actor relation types,
 * genres, rights basis, accession types and the rest of the seeded
 * vocabularies. Until now only 31 of them had an Arabic term_i18n row, so an
 * Arabic interface showed "Fonds", "Series" and "Custody" in English.
 *
 * Ships as a migration rather than a one-off script so every instance gets
 * the same labels on its next deploy.
 *
 * Safe on any install:
 * - a row is inserted only when the term exists with the same English name,
 *   so a seeded id that an instance has renamed or reused is left alone;
 * - an existing Arabic row is never touched, so curated translations win;
 * - re-running is a no-op.
 *
 * The labels are frozen here on purpose: a migration is a historical record.
 * down() removes only rows that still carry exactly the label inserted here.
 */

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    private function labels(): array
    {
        // [term id, English name, Arabic name]
        return [
            [179, 'Artwork component', 'مكوّن عمل فني'],
            [180, 'Artwork material', 'مادة عمل فني'],
            [181, 'Supporting documentation', 'وثائق داعمة'],
            [182, 'Supporting technology', 'تقنية داعمة'],
            [331, 'Deposit', 'إيداع'],
            [332, 'Gift', 'هبة'],
            [333, 'Purchase', 'شراء'],
            [334, 'Transfer', 'نقل'],
            [192, 'Accession alternative identifier', 'معرّف بديل للمقتنيات'],
            [193, 'Physical transfer', 'نقل مادي'],
            [335, 'High', 'مرتفعة'],
            [337, 'Low', 'منخفضة'],
            [336, 'Medium', 'متوسطة'],
            [338, 'Complete', 'مكتملة'],
            [340, 'In-Progress', 'قيد التنفيذ'],
            [339, 'Incomplete', 'غير مكتملة'],
            [330, 'Private transfer', 'نقل خاص'],
            [329, 'Public transfer', 'نقل عام'],
            [131, 'Corporate body', 'هيئة اعتبارية'],
            [133, 'Family', 'عائلة'],
            [132, 'Person', 'شخص'],
            [149, 'Other form', 'صيغة أخرى'],
            [148, 'Parallel form', 'صيغة موازية'],
            [165, 'Standardized form', 'صيغة معيارية'],
            [153, 'associative', 'ترابطية'],
            [200, 'controls', 'يتحكم في'],
            [152, 'family', 'عائلية'],
            [150, 'hierarchical', 'هرمية'],
            [201, 'is controlled by', 'يخضع لتحكم'],
            [203, 'is owned by', 'مملوك من قبل'],
            [209, 'is the associate of', 'شريك لـ'],
            [208, 'is the business partner of', 'شريك تجاري لـ'],
            [212, 'is the child of', 'ابن أو ابنة لـ'],
            [207, 'is the client of', 'عميل لـ'],
            [215, 'is the cousin of', 'ابن عم أو ابنة عم لـ'],
            [210, 'is the friend of', 'صديق لـ'],
            [217, 'is the grandchild of', 'حفيد أو حفيدة لـ'],
            [216, 'is the grandparent of', 'جد أو جدة لـ'],
            [202, 'is the owner of', 'مالك لـ'],
            [211, 'is the parent of', 'والد أو والدة لـ'],
            [204, 'is the predecessor of', 'سلف لـ'],
            [206, 'is the provider of', 'مزوّد لـ'],
            [213, 'is the sibling of', 'أخ أو أخت لـ'],
            [214, 'is the spouse of', 'زوج أو زوجة لـ'],
            [199, 'is the subordinate of', 'تابع لـ'],
            [205, 'is the successor of', 'خلف لـ'],
            [198, 'is the superior of', 'رئيس لـ'],
            [151, 'temporal', 'زمنية'],
            [128, 'Archival material', 'مواد أرشيفية'],
            [130, 'Artefact material', 'مواد أثرية'],
            [129, 'Published material', 'مواد منشورة'],
            [351, 'Public domain', 'ملكية عامة'],
            [350, 'Under copyright', 'محمي بحقوق النشر'],
            [383, 'Alphanumeric designations', 'التسميات الأبجدية الرقمية'],
            [382, 'Citation', 'الاستشهاد'],
            [381, 'Conservation', 'الصيانة'],
            [385, 'Processing information', 'معلومات المعالجة'],
            [384, 'Variant title information', 'معلومات العنوان البديل'],
            [342, 'Part', 'جزء'],
            [341, 'Whole', 'كامل'],
            [233, 'Full', 'كامل'],
            [235, 'Minimal', 'أدنى'],
            [234, 'Partial', 'جزئي'],
            [230, 'Final', 'نهائي'],
            [231, 'Revised', 'منقّح'],
            [196, 'Captions/Subtitles', 'الترجمات النصية / الترجمات المرئية'],
            [195, 'Chapters', 'الفصول'],
            [143, 'Compound', 'مركّب'],
            [166, 'External URI', 'معرّف URI خارجي'],
            [191, 'External file', 'ملف خارجي'],
            [186, 'Offline', 'غير متصل'],
            [141, 'Reference', 'مرجعي'],
            [311, 'Collection', 'مجموعة'],
            [312, 'dataset', 'مجموعة بيانات'],
            [313, 'event', 'حدث'],
            [314, 'image', 'صورة'],
            [315, 'interactive resource', 'مورد تفاعلي'],
            [316, 'moving image', 'صورة متحركة'],
            [317, 'physical object', 'قطعة مادية'],
            [318, 'service', 'خدمة'],
            [319, 'software', 'برمجيات'],
            [320, 'sound', 'صوت'],
            [321, 'still image', 'صورة ثابتة'],
            [322, 'text', 'نص'],
            [118, 'Accumulation', 'التجميع'],
            [221, 'Broadcasting', 'البث'],
            [117, 'Collection', 'الجمع'],
            [115, 'Contribution', 'المساهمة'],
            [113, 'Custody', 'الحيازة'],
            [220, 'Distribution', 'التوزيع'],
            [222, 'Manufacturing', 'التصنيع'],
            [114, 'Publication', 'النشر'],
            [386, 'Record-keeping activity', 'نشاط حفظ السجلات'],
            [219, 'Reproduction', 'الاستنساخ'],
            [164, 'associative', 'ترابطية'],
            [162, 'hierarchical', 'هرمية'],
            [163, 'temporal', 'زمنية'],
            [387, 'Advertisements', 'إعلانات'],
            [388, 'Albums', 'ألبومات'],
            [389, 'Architecture', 'عمارة'],
            [390, 'Blank forms', 'نماذج فارغة'],
            [391, 'Books', 'كتب'],
            [392, 'Broadsides', 'ملصقات حائطية'],
            [393, 'Cartoons (Commentary)', 'رسوم كاريكاتيرية (تعليق)'],
            [394, 'Catalogs', 'كتالوجات'],
            [395, 'Cityscapes', 'مناظر المدن'],
            [396, 'Clippings', 'قصاصات'],
            [397, 'Correspondence', 'مراسلات'],
            [398, 'Diaries', 'يوميات'],
            [399, 'Drawings', 'رسوم'],
            [400, 'Ephemera', 'مطبوعات عابرة'],
            [401, 'Essays', 'مقالات'],
            [402, 'Ethnography', 'إثنوغرافيا'],
            [403, 'Fieldnotes', 'ملاحظات ميدانية'],
            [405, 'Interviews', 'مقابلات'],
            [406, 'Landscapes', 'مناظر طبيعية'],
            [407, 'Leaflets', 'منشورات'],
            [408, 'Manuscripts', 'مخطوطات'],
            [409, 'Maps', 'خرائط'],
            [410, 'Miscellaneous Documents', 'وثائق متنوعة'],
            [411, 'Motion Pictures', 'أفلام سينمائية'],
            [412, 'Music', 'موسيقى'],
            [413, 'Narratives', 'سرديات'],
            [414, 'Paintings', 'لوحات'],
            [415, 'Pamphlets', 'كتيبات'],
            [416, 'Periodicals', 'دوريات'],
            [417, 'Petitions', 'عرائض'],
            [418, 'Photographs', 'صور فوتوغرافية'],
            [419, 'Physical Objects', 'قطع مادية'],
            [420, 'Poetry', 'شعر'],
            [421, 'Portraits', 'صور شخصية'],
            [422, 'Postcards', 'بطاقات بريدية'],
            [423, 'Posters', 'ملصقات'],
            [424, 'Prints', 'مطبوعات فنية'],
            [425, 'Programs', 'برامج'],
            [426, 'Recording logs', 'سجلات التسجيل'],
            [427, 'Scores', 'مدونات موسيقية'],
            [428, 'Sheet Music', 'نوتات موسيقية'],
            [429, 'Timetables', 'جداول مواعيد'],
            [430, 'Transcriptions', 'نصوص مفرّغة'],
            [326, 'Activity', 'نشاط'],
            [325, 'Business process', 'عملية تشغيلية'],
            [323, 'Function', 'وظيفة'],
            [324, 'Subfunction', 'وظيفة فرعية'],
            [327, 'Task', 'مهمة'],
            [328, 'Transaction', 'معاملة'],
            [184, 'Completed', 'مكتملة'],
            [238, 'Collection', 'مجموعة'],
            [241, 'File', 'ملف'],
            [236, 'Fonds', 'رصيد أرشيفي'],
            [299, 'Part', 'جزء'],
            [434, 'Record group', 'مجموعة سجلات'],
            [239, 'Series', 'سلسلة'],
            [237, 'Subfonds', 'رصيد فرعي'],
            [240, 'Subseries', 'سلسلة فرعية'],
            [301, 'cartographic', 'خرائطي'],
            [310, 'mixed material', 'مواد مختلطة'],
            [307, 'moving image', 'صورة متحركة'],
            [302, 'notated music', 'موسيقى مدوّنة'],
            [309, 'software, multimedia', 'برمجيات، وسائط متعددة'],
            [303, 'sound recording', 'تسجيل صوتي'],
            [304, 'sound recording-musical', 'تسجيل صوتي موسيقي'],
            [305, 'sound recording-nonmusical', 'تسجيل صوتي غير موسيقي'],
            [306, 'still image', 'صورة ثابتة'],
            [300, 'text', 'نص'],
            [308, 'three dimensional object', 'قطعة ثلاثية الأبعاد'],
            [276, 'Architectural drawing', 'رسم معماري'],
            [277, 'Cartographic material', 'مواد خرائطية'],
            [278, 'Graphic material', 'مواد مرئية'],
            [279, 'Moving images', 'صور متحركة'],
            [280, 'Multiple media', 'وسائط متعددة'],
            [281, 'Object', 'قطعة'],
            [282, 'Philatelic record', 'سجل طوابع بريدية'],
            [283, 'Sound recording', 'تسجيل صوتي'],
            [284, 'Technical drawing', 'رسم تقني'],
            [285, 'Textual record', 'سجل نصي'],
            [135, 'Audio', 'صوت'],
            [139, 'Other', 'أخرى'],
            [137, 'Text', 'نص'],
            [138, 'Video', 'فيديو'],
            [194, 'Accession event note', 'ملاحظة حدث المقتنيات'],
            [188, 'Actor occupation note', 'ملاحظة مهنة الفاعل'],
            [124, 'Archivist\'s note', 'ملاحظة أمين الأرشيف'],
            [275, 'Conservation note', 'ملاحظة الصيانة'],
            [123, 'Display note', 'ملاحظة العرض'],
            [125, 'General note', 'ملاحظة عامة'],
            [174, 'Language note', 'ملاحظة اللغة'],
            [127, 'Maintenance note', 'ملاحظة الصيانة الدورية'],
            [126, 'Other Descriptive Data', 'بيانات وصفية أخرى'],
            [120, 'Publication note', 'ملاحظة النشر'],
            [121, 'Source note', 'ملاحظة المصدر'],
            [119, 'Title note', 'ملاحظة العنوان'],
            [146, 'Artefact', 'قطعة أثرية'],
            [223, 'Box', 'صندوق'],
            [224, 'Cardboard box', 'صندوق كرتوني'],
            [145, 'Container', 'حاوية'],
            [227, 'Filing cabinet', 'خزانة ملفات'],
            [226, 'Folder', 'مجلد'],
            [225, 'Hollinger box', 'صندوق Hollinger'],
            [228, 'Map cabinet', 'خزانة خرائط'],
            [229, 'Shelf', 'رف'],
            [251, 'Archival description', 'وصف أرشيفي'],
            [254, 'Archival institution', 'مؤسسة أرشيفية'],
            [252, 'Authority record', 'سجل استناد'],
            [249, 'Collection', 'مجموعة'],
            [270, 'Digital object', 'كائن رقمي'],
            [253, 'Fonds', 'رصيد أرشيفي'],
            [243, 'Information object', 'كائن معلومات'],
            [244, 'Person/organization', 'شخص / مؤسسة'],
            [271, 'Physical object', 'كائن مادي'],
            [247, 'Term', 'مصطلح'],
            [289, 'Accompanying material', 'مواد مرافقة'],
            [291, 'Alpha-numeric designations', 'التسميات الأبجدية الرقمية'],
            [432, 'Cast note', 'ملاحظة طاقم التمثيل'],
            [288, 'Conservation', 'الصيانة'],
            [433, 'Credits note', 'ملاحظة شارة الأسماء'],
            [286, 'Edition', 'الطبعة'],
            [287, 'Physical description', 'الوصف المادي'],
            [290, 'Publisher\'s series', 'سلسلة الناشر'],
            [292, 'Rights', 'الحقوق'],
            [431, 'Signatures note', 'ملاحظة التواقيع'],
            [298, 'Attributions and conjectures', 'النسب والتخمينات'],
            [296, 'Continuation of title', 'تتمة العنوان'],
            [295, 'Parallel titles and other title information', 'العناوين الموازية ومعلومات العنوان الأخرى'],
            [294, 'Source of title proper', 'مصدر العنوان الأصلي'],
            [297, 'Statements of responsibility', 'بيانات المسؤولية'],
            [293, 'Variations in title', 'التغييرات في العنوان'],
            [155, 'date display', 'عرض التاريخ'],
            [154, 'description', 'الوصف'],
            [178, 'AIP relation', 'علاقة AIP'],
            [175, 'Accrual', 'إضافة لاحقة'],
            [169, 'Donor', 'مانح'],
            [187, 'Maintaining repository', 'المستودع المسؤول عن الصيانة'],
            [176, 'Related material descriptions', 'أوصاف المواد ذات الصلة'],
            [168, 'Right', 'حق'],
            [147, 'has Physical Object', 'يتضمن كائناً مادياً'],
            [161, 'name access points', 'نقاط الإتاحة للأسماء'],
            [263, 'Aboriginal', 'السكان الأصليون'],
            [259, 'Community', 'مجتمعية'],
            [264, 'Educational', 'تعليمية'],
            [255, 'International', 'دولية'],
            [265, 'Medical', 'طبية'],
            [266, 'Military', 'عسكرية'],
            [262, 'Municipal', 'بلدية'],
            [256, 'National', 'وطنية'],
            [267, 'Private', 'خاصة'],
            [258, 'Provincial/state', 'إقليمية / ولائية'],
            [257, 'Regional', 'مناطقية'],
            [260, 'Religious', 'دينية'],
            [261, 'University', 'جامعية'],
            [344, 'Discover', 'الاكتشاف'],
            [345, 'Display', 'العرض'],
            [346, 'Disseminate', 'النشر'],
            [347, 'Migrate', 'الترحيل'],
            [348, 'Modify', 'التعديل'],
            [349, 'Replicate', 'النسخ المتكرر'],
            [170, 'Copyright', 'حقوق النشر'],
            [218, 'Donor', 'المانح'],
            [171, 'License', 'ترخيص'],
            [173, 'Policy', 'سياسة'],
            [172, 'Statute', 'تشريع'],
            [158, 'publication', 'النشر'],
            [156, 'alternative label', 'تسمية بديلة'],
            [157, 'associative', 'ترابطية'],
            [358, 'Aboriginal Peoples', 'الشعوب الأصلية'],
            [359, 'Agriculture', 'الزراعة'],
            [360, 'Arts and Culture', 'الفنون والثقافة'],
            [361, 'Communication', 'الاتصالات'],
            [362, 'Education', 'التعليم'],
            [363, 'Environment', 'البيئة'],
            [364, 'Family / Domestic Life', 'الأسرة / الحياة المنزلية'],
            [365, 'Genealogical', 'علم الأنساب'],
            [366, 'Geography', 'الجغرافيا'],
            [367, 'Industry, Manufacturing and Commerce', 'الصناعة والتصنيع والتجارة'],
            [368, 'Labour', 'العمل'],
            [369, 'Law and Justice', 'القانون والعدالة'],
            [370, 'Medicine and Health', 'الطب والصحة'],
            [371, 'Military', 'الشؤون العسكرية'],
            [372, 'Natural Resources', 'الموارد الطبيعية'],
            [373, 'Politics and Government', 'السياسة والحكم'],
            [374, 'Populations', 'السكان'],
            [375, 'Recreation / Leisure / Sports', 'الترفيه / أوقات الفراغ / الرياضة'],
            [376, 'Religion', 'الدين'],
            [377, 'Science and Technology', 'العلوم والتكنولوجيا'],
            [378, 'Social Organizations and Activities', 'التنظيمات والأنشطة الاجتماعية'],
            [379, 'Transportation', 'النقل'],
            [380, 'Travel and Exploration', 'السفر والاستكشاف'],
            [190, 'Modification', 'تعديل'],
        ];
    }

    public function up(): void
    {
        if (! Schema::hasTable('term_i18n')) {
            return;
        }

        foreach ($this->labels() as [$id, $en, $ar]) {
            $matches = DB::table('term_i18n')->where(['id' => $id, 'culture' => 'en', 'name' => $en])->exists();
            $hasArabic = DB::table('term_i18n')->where(['id' => $id, 'culture' => 'ar'])->exists();
            if ($matches && ! $hasArabic) {
                DB::table('term_i18n')->insert(['id' => $id, 'culture' => 'ar', 'name' => $ar]);
            }
        }
    }

    public function down(): void
    {
        if (! Schema::hasTable('term_i18n')) {
            return;
        }

        foreach ($this->labels() as [$id, $en, $ar]) {
            DB::table('term_i18n')->where(['id' => $id, 'culture' => 'ar', 'name' => $ar])->delete();
        }
    }
};
