@extends('theme::layouts.1col')
@section('title', 'Containers')
@section('content')
@php
    // accession_allow_container_barcodes setting — when off, the Barcode
    // lookup card and Barcode column are hidden. Stored data persists.
    $barcodesEnabled = app(\AhgAccessionManage\Services\AccessionService::class)->containerBarcodesEnabled();
@endphp
<div class="container py-4">
<nav aria-label="{{ __('breadcrumb') }}" class="mb-3"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route("accession.browse") }}">Accessions</a></li><li class="breadcrumb-item"><a href="{{ route("accession.show",$accession->slug??"") }}">{{ e($accession->identifier??"") }}</a></li><li class="breadcrumb-item active">Containers</li></ol></nav><ul class="nav nav-tabs mb-4"><li class="nav-item"><a class="nav-link active" href="{{ route("accession.containers",$accession->id??0) }}">Containers</a></li><li class="nav-item"><a class="nav-link" href="{{ route("accession.rights",$accession->id??0) }}">Rights</a></li></ul>@if($barcodesEnabled)<div class="card mb-4"><div class="card-header"><i class="fas fa-barcode me-2"></i>{{ __('Barcode lookup') }}</div><div class="card-body"><div class="row g-2 align-items-end"><div class="col-sm-6 col-md-4"><label class="form-label">Scan or enter barcode <span class="badge bg-secondary ms-1">{{ __('Optional') }}</span></label><input type="text" class="form-control" placeholder="{{ __('Barcode...') }}"></div><div class="col-auto"><button type="button" class="btn btn-outline-primary"><i class="fas fa-search me-1"></i>{{ __('Lookup') }}</button></div></div></div></div>@endif<div class="card"><div class="card-header" style="background:var(--ahg-primary);color:#fff"><h5 class="mb-0">{{ __('Containers') }}</h5></div><div class="card-body p-0"><table class="table table-striped mb-0"><thead><tr><th>{{ __('Type') }}</th><th>{{ __('Name') }}</th>@if($barcodesEnabled)<th>{{ __('Barcode') }}</th>@endif<th>{{ __('Location') }}</th><th>{{ __('Condition') }}</th><th class="text-end">{{ __('Items') }}</th></tr></thead><tbody>@forelse($containers??[] as $c)<tr><td>{{ e($c->type??"") }}</td><td><strong>{{ e($c->name??$c->number??"") }}</strong></td>@if($barcodesEnabled)<td><code>{{ e($c->barcode??"") }}</code></td>@endif<td>{{ e($c->location??"") }}</td><td>{{ e($c->condition??"") }}</td><td class="text-end">{{ $c->item_count??0 }}</td></tr>@empty<tr><td colspan="{{ $barcodesEnabled ? 6 : 5 }}" class="text-muted text-center py-3">No containers.</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
