-- heratio#1231 - Research OS #9: Method Design Studio - discipline templates.
--
-- INSERT IGNORE keyed on the unique `code`, so re-running is idempotent and a
-- site that has hand-edited a template keeps its edits. The `guidance` column
-- is a JSON object: an ordered map of area-key => {label, prompt, placeholder}.
--
-- Guidance is intentionally JURISDICTION-NEUTRAL. Ethics / consent / data-
-- management prompts speak to general principles (informed consent, lawful
-- basis, retention, anonymisation) and never name a specific country's regime.
-- A site layers its own market module (GDPR, POPIA, IPSAS, etc.) on top.

INSERT IGNORE INTO `research_method_template`
  (`code`, `name`, `discipline`, `description`, `guidance`, `is_active`, `sort_order`, `created_at`, `updated_at`)
VALUES
('design-science', 'Design Science Research', 'Information Systems / Engineering',
 'Build-and-evaluate of an artefact (model, method, instantiation) against defined objectives, with rigorous demonstration and evaluation cycles.',
 '{"design":{"label":"Research design","prompt":"State the artefact you will build and the design-science cycle (problem identification, objectives, design, demonstration, evaluation, communication) you will follow.","placeholder":"e.g. We design a method artefact and evaluate it over two build-evaluate iterations."},"sampling":{"label":"Cases / evaluation settings","prompt":"Which cases, datasets, or settings will the artefact be demonstrated and evaluated in, and why are they representative?","placeholder":""},"data_sources":{"label":"Data sources","prompt":"What evidence feeds the design and the evaluation (logs, expert input, benchmark datasets)?","placeholder":""},"instruments":{"label":"Evaluation instruments","prompt":"How will the artefact be measured (metrics, expert criteria, technical benchmarks)?","placeholder":""},"coding_framework":{"label":"Analysis framework","prompt":"How will qualitative evaluation feedback be structured or coded, if any?","placeholder":""},"variables":{"label":"Constructs / variables","prompt":"List the design constructs and the evaluation criteria they map to.","placeholder":""},"validity":{"label":"Validity","prompt":"How do you establish that the artefact actually solves the stated problem (construct, internal, external validity)?","placeholder":""},"reliability":{"label":"Rigour / reliability","prompt":"How is the build-evaluate process documented so it can be inspected and repeated?","placeholder":""},"ethics":{"label":"Ethics","prompt":"Identify any human or organisational involvement and the ethical review obtained.","placeholder":""},"consent":{"label":"Consent","prompt":"How is informed consent obtained from any experts or participants involved in evaluation?","placeholder":""},"bias_control":{"label":"Bias control","prompt":"How do you guard against designer bias in evaluating your own artefact?","placeholder":""},"reproducibility":{"label":"Reproducibility","prompt":"How will the artefact, its inputs, and its evaluation be packaged so others can reproduce the result?","placeholder":""},"data_management":{"label":"Data management","prompt":"Where are artefacts, datasets, and evaluation records stored, with what retention and access controls?","placeholder":""}}',
 1, 10, NOW(), NOW()),

('archival-method', 'Archival / Documentary Method', 'Archival Science / History',
 'Systematic interrogation of records and finding aids: provenance, original order, diplomatics, and source criticism of archival documents.',
 '{"design":{"label":"Research design","prompt":"Describe your archival approach: which fonds/collections, what arrangement you respect (provenance, original order), and your reading strategy.","placeholder":""},"sampling":{"label":"Record selection","prompt":"How do you select records and series from the corpus? State inclusion / exclusion criteria.","placeholder":""},"data_sources":{"label":"Sources","prompt":"List archives, repositories, and record groups consulted, with their custodial context.","placeholder":""},"instruments":{"label":"Reading / transcription instruments","prompt":"What tools or templates structure your transcription, calendaring, or item-level notes?","placeholder":""},"coding_framework":{"label":"Coding / indexing framework","prompt":"How will you index or thematically code the records (subjects, actors, events)?","placeholder":""},"variables":{"label":"Analytical dimensions","prompt":"Which dimensions do you track across records (date, creator, document type, authenticity)?","placeholder":""},"validity":{"label":"Source criticism / validity","prompt":"How do you assess authenticity, reliability, and integrity of each record (diplomatics, external/internal criticism)?","placeholder":""},"reliability":{"label":"Reliability","prompt":"How are transcriptions and interpretations checked for consistency?","placeholder":""},"ethics":{"label":"Ethics","prompt":"Address access restrictions, third-party privacy in records, and any sensitivity of the material.","placeholder":""},"consent":{"label":"Consent / permissions","prompt":"What permissions are needed from custodians or rights holders to use and reproduce records?","placeholder":""},"bias_control":{"label":"Bias control","prompt":"How do you account for gaps and silences in the archive and the bias of what was kept?","placeholder":""},"reproducibility":{"label":"Reproducibility / citation","prompt":"How are records cited (reference codes, repository) so another scholar can locate the same item?","placeholder":""},"data_management":{"label":"Data management","prompt":"How are surrogates, transcriptions, and notes stored, with what retention and rights handling?","placeholder":""}}',
 1, 20, NOW(), NOW()),

('ethnography', 'Ethnography', 'Anthropology / Sociology',
 'Immersive fieldwork producing thick description of a community or setting through participant observation and field notes.',
 '{"design":{"label":"Research design","prompt":"Describe the field site, your role (participant / observer), and the duration and rhythm of fieldwork.","placeholder":""},"sampling":{"label":"Site & participant selection","prompt":"How are the setting and informants chosen (purposive, snowball)? Who is included?","placeholder":""},"data_sources":{"label":"Data sources","prompt":"What data will you gather (field notes, informal interviews, artefacts, photos)?","placeholder":""},"instruments":{"label":"Instruments","prompt":"What field-note protocol, interview guides, or observation grids will you use?","placeholder":""},"coding_framework":{"label":"Coding framework","prompt":"How will field notes be coded (open / axial, thematic categories)?","placeholder":""},"variables":{"label":"Sensitising concepts","prompt":"Which concepts or themes orient your observation without over-determining it?","placeholder":""},"validity":{"label":"Trustworthiness","prompt":"How do you establish credibility (prolonged engagement, triangulation, member checking)?","placeholder":""},"reliability":{"label":"Dependability","prompt":"How is the inquiry audit-trailed so the process is dependable?","placeholder":""},"ethics":{"label":"Ethics","prompt":"Address the power relationship, potential harm, anonymity of the community, and ethical review.","placeholder":""},"consent":{"label":"Consent","prompt":"How is informed, ongoing consent obtained in a setting where consent is processual?","placeholder":""},"bias_control":{"label":"Reflexivity / bias control","prompt":"How do you reflexively account for your own positionality and its effect on the field?","placeholder":""},"reproducibility":{"label":"Transferability","prompt":"What contextual detail lets readers judge transferability to other settings?","placeholder":""},"data_management":{"label":"Data management","prompt":"How are field notes and recordings secured, anonymised, retained, and eventually disposed of?","placeholder":""}}',
 1, 30, NOW(), NOW()),

('case-study', 'Case Study', 'Social Science / Management',
 'In-depth study of one or more bounded cases using multiple sources of evidence converging on the research questions.',
 '{"design":{"label":"Research design","prompt":"State whether single or multiple case, holistic or embedded, and how the case is bounded.","placeholder":""},"sampling":{"label":"Case selection","prompt":"How and why are cases selected (typical, extreme, theoretical replication)?","placeholder":""},"data_sources":{"label":"Data sources","prompt":"List the multiple evidence sources (interviews, documents, observation, archival records).","placeholder":""},"instruments":{"label":"Instruments / protocol","prompt":"Describe the case-study protocol and any interview or document-review instruments.","placeholder":""},"coding_framework":{"label":"Coding framework","prompt":"How will evidence be coded and pattern-matched against propositions?","placeholder":""},"variables":{"label":"Propositions / constructs","prompt":"State the theoretical propositions or constructs guiding data collection.","placeholder":""},"validity":{"label":"Validity","prompt":"Address construct, internal, and external validity (chain of evidence, pattern matching, replication logic).","placeholder":""},"reliability":{"label":"Reliability","prompt":"How does the case-study protocol and database make the study repeatable?","placeholder":""},"ethics":{"label":"Ethics","prompt":"Address organisational and participant confidentiality and ethical clearance.","placeholder":""},"consent":{"label":"Consent","prompt":"How is informed consent obtained from organisations and individual informants?","placeholder":""},"bias_control":{"label":"Bias control","prompt":"How do you mitigate selection and confirmation bias across sources?","placeholder":""},"reproducibility":{"label":"Reproducibility","prompt":"How is the case-study database maintained for inspection and replication?","placeholder":""},"data_management":{"label":"Data management","prompt":"Where is case evidence stored, with what access controls and retention?","placeholder":""}}',
 1, 40, NOW(), NOW()),

('qualitative', 'Qualitative (General)', 'General',
 'General interpretive approach drawing on interviews, documents, and observation to build themes and meaning.',
 '{"design":{"label":"Research design","prompt":"Describe the qualitative approach and its philosophical stance (interpretivist, constructivist).","placeholder":""},"sampling":{"label":"Sampling","prompt":"State the sampling strategy and how you judge sufficiency (saturation, information power).","placeholder":""},"data_sources":{"label":"Data sources","prompt":"What qualitative data will you collect (interviews, focus groups, documents)?","placeholder":""},"instruments":{"label":"Instruments","prompt":"Describe interview / focus-group guides and how they were developed and piloted.","placeholder":""},"coding_framework":{"label":"Coding framework","prompt":"What coding and theme-development method will you use (thematic analysis, framework, grounded theory)?","placeholder":""},"variables":{"label":"Concepts","prompt":"What initial concepts or topics orient analysis?","placeholder":""},"validity":{"label":"Trustworthiness","prompt":"How do you ensure credibility, transferability, dependability, confirmability?","placeholder":""},"reliability":{"label":"Coding consistency","prompt":"How is coding consistency handled (codebook, inter-coder agreement)?","placeholder":""},"ethics":{"label":"Ethics","prompt":"Address potential harm, confidentiality, and ethical review.","placeholder":""},"consent":{"label":"Consent","prompt":"How is informed consent obtained and documented?","placeholder":""},"bias_control":{"label":"Reflexivity / bias control","prompt":"How is researcher influence acknowledged and managed?","placeholder":""},"reproducibility":{"label":"Auditability","prompt":"How is the analytic trail recorded so the route from data to findings is transparent?","placeholder":""},"data_management":{"label":"Data management","prompt":"How are recordings, transcripts, and codes stored, anonymised, and retained?","placeholder":""}}',
 1, 50, NOW(), NOW()),

('quantitative', 'Quantitative (General)', 'General',
 'Measurement-based approach testing hypotheses with statistical analysis of numeric data.',
 '{"design":{"label":"Research design","prompt":"State the design (experimental, quasi-experimental, survey, correlational) and rationale.","placeholder":""},"sampling":{"label":"Sampling","prompt":"Define population, sampling frame, technique, and target sample size with power justification.","placeholder":""},"data_sources":{"label":"Data sources","prompt":"What numeric data will you collect or obtain, and from where?","placeholder":""},"instruments":{"label":"Instruments","prompt":"Describe measurement instruments, their scales, and prior validation.","placeholder":""},"coding_framework":{"label":"Data coding","prompt":"How are responses coded and cleaned for analysis?","placeholder":""},"variables":{"label":"Variables","prompt":"List independent, dependent, control, and confounding variables with operational definitions.","placeholder":""},"validity":{"label":"Validity","prompt":"Address measurement validity and internal / external validity of the design.","placeholder":""},"reliability":{"label":"Reliability","prompt":"State reliability evidence (Cronbach alpha, test-retest) for the instruments.","placeholder":""},"ethics":{"label":"Ethics","prompt":"Address participant risk, confidentiality, and ethical clearance.","placeholder":""},"consent":{"label":"Consent","prompt":"How is informed consent obtained for data collection?","placeholder":""},"bias_control":{"label":"Bias control","prompt":"How do you control selection, response, and analysis bias (randomisation, blinding, pre-registration)?","placeholder":""},"reproducibility":{"label":"Reproducibility","prompt":"How will data and analysis code be shared so results can be reproduced?","placeholder":""},"data_management":{"label":"Data management","prompt":"Where are the dataset and analysis files stored, with what retention and access controls?","placeholder":""}}',
 1, 60, NOW(), NOW()),

('mixed-methods', 'Mixed Methods', 'General',
 'Combines quantitative and qualitative strands with an explicit integration design (convergent, explanatory, exploratory).',
 '{"design":{"label":"Research design","prompt":"State the mixed-methods design (convergent, explanatory sequential, exploratory sequential) and the point of integration.","placeholder":""},"sampling":{"label":"Sampling","prompt":"Describe sampling for each strand and how the samples relate (nested, parallel).","placeholder":""},"data_sources":{"label":"Data sources","prompt":"List both quantitative and qualitative data sources.","placeholder":""},"instruments":{"label":"Instruments","prompt":"Describe instruments for each strand and any that bridge the two.","placeholder":""},"coding_framework":{"label":"Analysis framework","prompt":"How are the strands analysed and then integrated (joint display, data transformation)?","placeholder":""},"variables":{"label":"Constructs / variables","prompt":"List the variables and qualitative concepts and where they meet.","placeholder":""},"validity":{"label":"Validity / legitimation","prompt":"Address validity for each strand and the legitimation of the integrated inference.","placeholder":""},"reliability":{"label":"Reliability","prompt":"How is rigour maintained in both strands?","placeholder":""},"ethics":{"label":"Ethics","prompt":"Address ethical considerations spanning both strands.","placeholder":""},"consent":{"label":"Consent","prompt":"How is consent handled where participants contribute to more than one strand?","placeholder":""},"bias_control":{"label":"Bias control","prompt":"How is bias controlled in each strand and at integration?","placeholder":""},"reproducibility":{"label":"Reproducibility","prompt":"How are both datasets and the integration procedure documented for reuse?","placeholder":""},"data_management":{"label":"Data management","prompt":"How are the combined data assets stored, linked, and retained securely?","placeholder":""}}',
 1, 70, NOW(), NOW()),

('discourse-analysis', 'Discourse Analysis', 'Linguistics / Media Studies',
 'Close analysis of how language constructs meaning, identity, and power across a corpus of texts or talk.',
 '{"design":{"label":"Research design","prompt":"State the discourse-analytic approach (critical discourse analysis, conversation analysis, corpus-assisted) and unit of analysis.","placeholder":""},"sampling":{"label":"Corpus selection","prompt":"How is the text / talk corpus assembled and bounded?","placeholder":""},"data_sources":{"label":"Data sources","prompt":"What texts, transcripts, or media make up the corpus, and where are they from?","placeholder":""},"instruments":{"label":"Analytic instruments","prompt":"What transcription conventions or analytic categories will you apply?","placeholder":""},"coding_framework":{"label":"Coding framework","prompt":"What linguistic / rhetorical features and discursive strategies will you code?","placeholder":""},"variables":{"label":"Analytic dimensions","prompt":"Which discursive dimensions (modality, agency, framing) do you track?","placeholder":""},"validity":{"label":"Validity","prompt":"How is interpretive validity established (close reading, deviant cases, intertextual grounding)?","placeholder":""},"reliability":{"label":"Consistency","prompt":"How is analytic consistency handled across the corpus?","placeholder":""},"ethics":{"label":"Ethics","prompt":"Address the status of the texts (public vs private), authorship, and any privacy concerns.","placeholder":""},"consent":{"label":"Consent","prompt":"Where talk is recorded from participants, how is consent obtained?","placeholder":""},"bias_control":{"label":"Bias control","prompt":"How do you guard against cherry-picking and confirm your reading against the full corpus?","placeholder":""},"reproducibility":{"label":"Reproducibility","prompt":"How is the corpus and coding scheme documented so another analyst could follow it?","placeholder":""},"data_management":{"label":"Data management","prompt":"How is the corpus stored and rights-cleared, with what retention?","placeholder":""}}',
 1, 80, NOW(), NOW()),

('historical-method', 'Historical Method', 'History',
 'Reconstruction and interpretation of the past through critical evaluation of primary and secondary sources.',
 '{"design":{"label":"Research design","prompt":"State the historical question, period, and the interpretive frame (narrative, comparative, microhistory).","placeholder":""},"sampling":{"label":"Source selection","prompt":"How do you select sources across archives and how do you handle gaps?","placeholder":""},"data_sources":{"label":"Sources","prompt":"List primary and secondary sources and their provenance.","placeholder":""},"instruments":{"label":"Note / extract instruments","prompt":"What note-taking, calendaring, or extraction templates structure your reading?","placeholder":""},"coding_framework":{"label":"Thematic framework","prompt":"How do you organise evidence thematically or chronologically?","placeholder":""},"variables":{"label":"Analytical threads","prompt":"Which actors, events, and causal threads do you trace?","placeholder":""},"validity":{"label":"Source criticism","prompt":"How do you apply external and internal source criticism to establish authenticity and reliability?","placeholder":""},"reliability":{"label":"Corroboration","prompt":"How do you corroborate claims across independent sources?","placeholder":""},"ethics":{"label":"Ethics","prompt":"Address living subjects, sensitive histories, and any access restrictions.","placeholder":""},"consent":{"label":"Permissions","prompt":"What permissions are needed to consult and reproduce restricted sources?","placeholder":""},"bias_control":{"label":"Bias control","prompt":"How do you account for the bias of surviving sources and your own interpretive standpoint?","placeholder":""},"reproducibility":{"label":"Citation / verifiability","prompt":"How are sources cited so claims can be verified at the original?","placeholder":""},"data_management":{"label":"Data management","prompt":"How are surrogates, transcriptions, and research notes stored and retained?","placeholder":""}}',
 1, 90, NOW(), NOW()),

('legal-policy', 'Legal / Policy Analysis', 'Law / Public Policy',
 'Doctrinal and policy analysis of legal instruments, case law, and regulatory frameworks. Treat the legal corpus as jurisdiction-neutral; name the jurisdiction in your answers, not in the template.',
 '{"design":{"label":"Research design","prompt":"State whether the analysis is doctrinal, comparative, or socio-legal, and the jurisdiction(s) in scope.","placeholder":""},"sampling":{"label":"Source / jurisdiction selection","prompt":"Which instruments, cases, and jurisdictions are in scope and why?","placeholder":""},"data_sources":{"label":"Legal sources","prompt":"List statutes, regulations, case law, treaties, and policy documents consulted.","placeholder":""},"instruments":{"label":"Analytic instruments","prompt":"What framework structures the analysis (issue-rule-application-conclusion, comparative matrix)?","placeholder":""},"coding_framework":{"label":"Coding framework","prompt":"How will provisions and holdings be categorised and compared?","placeholder":""},"variables":{"label":"Analytical dimensions","prompt":"Which legal dimensions (scope, obligations, remedies, sanctions) do you compare?","placeholder":""},"validity":{"label":"Validity / authority","prompt":"How do you ensure you rely on authoritative, current sources of law?","placeholder":""},"reliability":{"label":"Reliability","prompt":"How do you verify the currency and accuracy of cited provisions?","placeholder":""},"ethics":{"label":"Ethics","prompt":"Address any empirical component involving people and the ethical clearance required.","placeholder":""},"consent":{"label":"Consent","prompt":"If interviews with practitioners are used, how is consent handled?","placeholder":""},"bias_control":{"label":"Bias control","prompt":"How do you present competing interpretations fairly rather than selectively?","placeholder":""},"reproducibility":{"label":"Reproducibility","prompt":"How are citations to law given so the reader can locate the exact provision?","placeholder":""},"data_management":{"label":"Data management","prompt":"How are collected legal materials and any empirical data stored and retained?","placeholder":""}}',
 1, 100, NOW(), NOW()),

('computational-dh', 'Computational / Digital Humanities', 'Digital Humanities',
 'Computational treatment of cultural data: text mining, network analysis, mapping, and modelling over digitised corpora.',
 '{"design":{"label":"Research design","prompt":"State the computational approach (text mining, network analysis, topic modelling, GIS) and how it answers the humanities question.","placeholder":""},"sampling":{"label":"Corpus construction","prompt":"How is the corpus built, cleaned, and bounded? What is included or excluded?","placeholder":""},"data_sources":{"label":"Data sources","prompt":"What digitised collections, datasets, or APIs feed the analysis?","placeholder":""},"instruments":{"label":"Tools / pipeline","prompt":"What software, libraries, and pipeline steps will you use?","placeholder":""},"coding_framework":{"label":"Annotation / coding","prompt":"How is the corpus annotated, tagged, or feature-engineered?","placeholder":""},"variables":{"label":"Features / parameters","prompt":"List the features, metrics, and model parameters you analyse.","placeholder":""},"validity":{"label":"Validity","prompt":"How do you validate computational results against close reading or ground truth?","placeholder":""},"reliability":{"label":"Reliability","prompt":"How stable are results to parameter and pre-processing choices?","placeholder":""},"ethics":{"label":"Ethics","prompt":"Address rights in the corpus, sensitive content, and any algorithmic harm.","placeholder":""},"consent":{"label":"Consent / rights","prompt":"What licensing or consent governs reuse of the source data?","placeholder":""},"bias_control":{"label":"Bias control","prompt":"How do you surface and account for bias in data, tools, and models? If a model assists analysis it must run through the institutional AI gateway, never a direct node.","placeholder":""},"reproducibility":{"label":"Reproducibility","prompt":"How will code, parameters, and environment be shared so the analysis can be re-run?","placeholder":""},"data_management":{"label":"Data management","prompt":"Where are the corpus, derived datasets, and code archived, with what versioning and retention?","placeholder":""}}',
 1, 110, NOW(), NOW());

-- Protocol status taxonomy for the Dropdown Manager (VARCHAR-backed, never ENUM).
INSERT IGNORE INTO `ahg_dropdown`
  (`taxonomy`, `taxonomy_label`, `taxonomy_section`, `code`, `label`, `color`, `icon`, `sort_order`, `is_active`, `created_at`)
VALUES
('method_protocol_status', 'Method Protocol Status', 'research', 'draft', 'Draft', 'secondary', NULL, 10, 1, NOW()),
('method_protocol_status', 'Method Protocol Status', 'research', 'in_review', 'In Review', 'info', NULL, 20, 1, NOW()),
('method_protocol_status', 'Method Protocol Status', 'research', 'final', 'Final', 'success', NULL, 30, 1, NOW());
