<?php

/**
 * UiStringService - load, edit and persist UI translation strings.
 *
 * Heratio - In-app UI-string editor (issue #54 MVP, #57 backend swap).
 *
 * Storage of record (#57):
 *   - Reads + writes go through the `ui_string` table (one row per
 *     (key, culture) pair).
 *   - lang/{locale}.json files remain on disk as a deploy-time fallback.
 *     The DbAwareLoader merges DB rows on top of JSON values per request,
 *     so if a culture has zero DB rows the app still serves the JSON.
 *   - The one-shot `php artisan ahg:translation:import-json-to-db` command
 *     seeds the table from the JSON catalogue.
 *
 * Copyright (C) 2026 Johan Pieterse / Plain Sailing iSystems
 * Licensed under AGPL-3.0-or-later. See LICENSE.
 */

namespace AhgTranslation\Services;

use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class UiStringService
{
    /**
     * Locales enabled in the app (driven by ahg_settings 'i18n_languages' rows
     * with editable=1, falling back to lang/*.json on disk).
     */
    public function enabledLocales(): array
    {
        $codes = [];
        try {
            if (Schema::hasTable('setting')) {
                $codes = DB::table('setting')
                    ->where('scope', 'i18n_languages')
                    ->where('editable', 1)
                    ->pluck('name')
                    ->toArray();
            }
        } catch (\Throwable $e) {
            // fall through
        }
        if (empty($codes)) {
            $files = glob(base_path('lang/*.json')) ?: [];
            $codes = array_map(fn ($f) => pathinfo($f, PATHINFO_FILENAME), $files);
        }
        sort($codes);
        return $codes ?: ['en'];
    }

    /**
     * Load lang/en.json as the source of truth for translation keys.
     * en values are themselves the canonical English strings.
     *
     * Kept on the filesystem because the source list of keys is generated by
     * code-scan tooling that walks `__('...')` call sites and writes en.json;
     * having that as the source-of-truth on disk keeps the developer
     * round-trip (add a new __() in code, run extract, see it in the editor)
     * unchanged. The editor matrix overlays per-culture DB rows on top.
     */
    public function sourceKeys(): array
    {
        $path = base_path('lang/en.json');
        if (!is_readable($path)) {
            return [];
        }
        $json = json_decode((string) file_get_contents($path), true);
        return is_array($json) ? $json : [];
    }

    /**
     * Load every (key, value) pair for a culture.
     *
     * Order:
     *   1. ui_string rows for this culture (system of record)
     *   2. lang/{culture}.json values for keys not yet promoted to ui_string
     *
     * The merge gives a fresh install (zero DB rows) the same surface area
     * as the file-only era, while a fully-imported install reads only DB.
     */
    public function localeMap(string $locale): array
    {
        $this->guardLocale($locale);

        $fileMap = [];
        $path = base_path('lang/' . $locale . '.json');
        if (is_readable($path)) {
            $decoded = json_decode((string) file_get_contents($path), true);
            if (is_array($decoded)) {
                $fileMap = $decoded;
            }
        }

        $dbMap = [];
        try {
            if (Schema::hasTable('ui_string')) {
                DB::table('ui_string')
                    ->where('culture', $locale)
                    ->select(['key', 'value'])
                    ->orderBy('id')
                    ->chunk(2000, function ($rows) use (&$dbMap) {
                        foreach ($rows as $r) {
                            $val = (string) ($r->value ?? '');
                            if ($val !== '') {
                                $dbMap[(string) $r->key] = $val;
                            }
                        }
                    });
            }
        } catch (\Throwable $e) {
            // Fall back to the file-only map if DB is unavailable.
        }

        return array_merge($fileMap, $dbMap);
    }

    /**
     * Upsert a single (key, culture, value) into ui_string.
     *
     * - When $value is null or '', the key is deleted (matches the legacy
     *   "unset" semantics of the JSON write path).
     * - When $value is set, INSERT ... ON DUPLICATE KEY UPDATE.
     * - Flushes the per-process cache on the DbAwareLoader so the next
     *   __() call in the same request sees the new value.
     *
     * Returns the full key=>value map for this culture (post-write), to keep
     * the legacy callsites that wanted the snapshot.
     */
    public function setKey(string $locale, string $key, ?string $value): array
    {
        $this->guardLocale($locale);
        if ($key === '') {
            throw new \InvalidArgumentException('key cannot be empty');
        }

        if (!Schema::hasTable('ui_string')) {
            throw new \RuntimeException('ui_string table missing - boot the app once to auto-install');
        }

        if ($value === null || $value === '') {
            DB::table('ui_string')
                ->where('culture', $locale)
                ->where('key', $key)
                ->delete();
        } else {
            DB::table('ui_string')->upsert(
                [[
                    'key'        => $key,
                    'culture'    => $locale,
                    'value'      => $value,
                    'updated_at' => now(),
                ]],
                ['key', 'culture'],
                ['value', 'updated_at']
            );
        }

        // Drop the in-memory cache on the DB-aware loader so subsequent
        // __() calls in the same request see the fresh value. The loader
        // is registered as a decorator over translation.loader, so the
        // current Translator instance still holds the now-stale 'loaded'
        // map for this culture - reset it too (one query next call).
        try {
            $loader = app('translation.loader');
            if ($loader instanceof \AhgTranslation\Translation\DbAwareLoader) {
                $loader->flush($locale);
            }
            $translator = app('translator');
            // Translator caches per-locale loaded lines under
            // $loaded['*']['*'][$locale]; reflection lets us drop just
            // this culture's cache without touching the rest.
            $reflection = new \ReflectionProperty($translator, 'loaded');
            $reflection->setAccessible(true);
            $loaded = $reflection->getValue($translator);
            if (isset($loaded['*']['*'][$locale])) {
                unset($loaded['*']['*'][$locale]);
                $reflection->setValue($translator, $loaded);
            }
        } catch (\Throwable $e) {
            // Cache flush is best-effort; the next request gets a fresh load
            // anyway (the per-process cache is a per-request convenience).
        }

        return $this->localeMap($locale);
    }

    /**
     * Build the matrix the editor view consumes.
     *
     * @param string|null $localeFilter   restrict to a single locale (default: all enabled)
     * @param string|null $missingLocale  only return rows missing in this locale
     * @param string|null $contains       case-insensitive substring (matches key OR any locale value)
     * @param int         $limit          page size (0 = unlimited; sensible default for MVP)
     * @param int         $offset
     * @param string|null $changedSince   ISO date 'YYYY-MM-DD'; only rows that have an
     *                                    approved ui_string_change row dated >= this for
     *                                    the locale-of-interest (defaults to localeFilter
     *                                    if set, else any locale)
     * @return array{rows:array, total:int, locales:array}
     */
    public function matrix(
        ?string $localeFilter = null,
        ?string $missingLocale = null,
        ?string $contains = null,
        int $limit = 200,
        int $offset = 0,
        ?string $changedSince = null
    ): array {
        $allLocales = $this->enabledLocales();
        $locales = $localeFilter
            ? (in_array($localeFilter, $allLocales, true) ? [$localeFilter] : $allLocales)
            : $allLocales;

        // Pre-load every locale once so we don't hit the DB in a loop.
        $maps = ['en' => $this->localeMap('en')];
        foreach ($locales as $code) {
            if (!isset($maps[$code])) {
                $maps[$code] = $this->localeMap($code);
            }
        }

        $keys = array_keys($maps['en'] ?: []);
        sort($keys);

        // Filter - missing
        if ($missingLocale && in_array($missingLocale, $allLocales, true)) {
            $target = $maps[$missingLocale] ?? [];
            $keys = array_values(array_filter(
                $keys,
                fn ($k) => !array_key_exists($k, $target) || (string) ($target[$k] ?? '') === ''
            ));
        }

        // Filter - substring
        if ($contains !== null && $contains !== '') {
            $needle = mb_strtolower($contains);
            $keys = array_values(array_filter($keys, function ($k) use ($needle, $maps, $locales) {
                if (mb_stripos($k, $needle) !== false) return true;
                foreach ($locales as $code) {
                    $v = (string) ($maps[$code][$k] ?? '');
                    if ($v !== '' && mb_stripos($v, $needle) !== false) return true;
                }
                $en = (string) ($maps['en'][$k] ?? '');
                if ($en !== '' && mb_stripos($en, $needle) !== false) return true;
                return false;
            }));
        }

        // Filter - changed since: surfaces only keys that have an approved
        // change row dated >= the supplied date. Scope to the current locale
        // when one is selected, else any locale. Uses ui_string_change as the
        // audit log (post-#57 it's the unified pending+history table).
        if ($changedSince !== null && $changedSince !== '') {
            try {
                $since = (new \DateTimeImmutable($changedSince))->format('Y-m-d 00:00:00');
            } catch (\Throwable $e) {
                $since = null;
            }
            if ($since && Schema::hasTable('ui_string_change')) {
                $q = DB::table('ui_string_change')
                    ->where('status', 'approved')
                    ->where('reviewed_at', '>=', $since);
                if ($localeFilter && in_array($localeFilter, $allLocales, true)) {
                    $q->where('locale', $localeFilter);
                }
                $changedKeys = $q->pluck('key_text')->all();
                $changedSet = array_flip(array_map('strval', $changedKeys));
                $keys = array_values(array_filter($keys, fn ($k) => isset($changedSet[$k])));
            } else {
                $keys = [];
            }
        }

        $total = count($keys);
        if ($limit > 0) {
            $keys = array_slice($keys, $offset, $limit);
        }

        $rows = [];
        foreach ($keys as $k) {
            $row = ['key' => $k, 'en' => (string) ($maps['en'][$k] ?? $k), 'translations' => []];
            foreach ($locales as $code) {
                if ($code === 'en') continue;
                $v = $maps[$code][$k] ?? null;
                $row['translations'][$code] = [
                    'value'  => $v === null ? null : (string) $v,
                    'missing'=> ($v === null || (string) $v === ''),
                ];
            }
            $rows[] = $row;
        }

        return [
            'rows'    => $rows,
            'total'   => $total,
            'locales' => array_values(array_filter($locales, fn ($c) => $c !== 'en')),
        ];
    }

    /**
     * Insert a pending change row (editor save, or admin opt-in to review).
     * Does NOT touch ui_string - applyApproved() does that.
     */
    public function submitChange(int $userId, string $locale, string $key, ?string $value): int
    {
        $this->guardLocale($locale);
        $current = $this->localeMap($locale);
        $old = $current[$key] ?? null;
        return DB::table('ui_string_change')->insertGetId([
            'locale'                => $locale,
            'key_text'              => $key,
            'old_value'             => $old,
            'new_value'             => $value,
            'status'                => 'pending',
            'submitted_by_user_id'  => $userId,
            'submitted_at'          => now(),
        ]);
    }

    /**
     * Apply an approved change to ui_string + write the audit row.
     * Use this for the immediate-approve path (admin without ?review=1)
     * AND for the approve-pending path (admin clicking Approve in the queue).
     */
    public function applyApproved(int $userId, string $locale, string $key, ?string $value, ?int $pendingId = null, ?string $note = null): int
    {
        $current = $this->localeMap($locale);
        $old = $current[$key] ?? null;
        $this->setKey($locale, $key, $value);

        if ($pendingId) {
            DB::table('ui_string_change')->where('id', $pendingId)->update([
                'status'              => 'approved',
                'reviewed_by_user_id' => $userId,
                'reviewed_at'         => now(),
                'review_note'         => $note,
            ]);
            return (int) $pendingId;
        }

        return DB::table('ui_string_change')->insertGetId([
            'locale'                => $locale,
            'key_text'              => $key,
            'old_value'             => $old,
            'new_value'             => $value,
            'status'                => 'approved',
            'submitted_by_user_id'  => $userId,
            'submitted_at'          => now(),
            'reviewed_by_user_id'   => $userId,
            'reviewed_at'           => now(),
            'review_note'           => $note,
        ]);
    }

    public function rejectPending(int $userId, int $pendingId, ?string $note = null): bool
    {
        return DB::table('ui_string_change')
            ->where('id', $pendingId)->where('status', 'pending')
            ->update([
                'status'              => 'rejected',
                'reviewed_by_user_id' => $userId,
                'reviewed_at'         => now(),
                'review_note'         => $note,
            ]) > 0;
    }

    /**
     * History rows for a single (locale, key) pair, newest first. Includes
     * pending + approved + rejected entries so the editor sees the full chain
     * of edits, who made them, and which were ultimately applied.
     */
    public function historyFor(string $locale, string $key, int $limit = 50): \Illuminate\Support\Collection
    {
        $this->guardLocale($locale);
        if (!Schema::hasTable('ui_string_change')) {
            return collect();
        }
        return DB::table('ui_string_change as c')
            ->leftJoin('user as us', 'us.id', '=', 'c.submitted_by_user_id')
            ->leftJoin('actor_i18n as as_i18n', function ($j) {
                $j->on('as_i18n.id', '=', 'us.id')->where('as_i18n.culture', '=', 'en');
            })
            ->leftJoin('user as ur', 'ur.id', '=', 'c.reviewed_by_user_id')
            ->leftJoin('actor_i18n as ar_i18n', function ($j) {
                $j->on('ar_i18n.id', '=', 'ur.id')->where('ar_i18n.culture', '=', 'en');
            })
            ->where('c.locale', $locale)
            ->where('c.key_text', $key)
            ->orderByDesc('c.submitted_at')
            ->limit($limit)
            ->select(
                'c.*',
                'us.username as submitter_username',
                'as_i18n.authorized_form_of_name as submitter_name',
                'ur.username as reviewer_username',
                'ar_i18n.authorized_form_of_name as reviewer_name'
            )
            ->get();
    }

    public function pendingChanges(?string $locale = null): \Illuminate\Support\Collection
    {
        $q = DB::table('ui_string_change as c')
            ->leftJoin('user as u', 'u.id', '=', 'c.submitted_by_user_id')
            ->leftJoin('actor_i18n as ai', function ($j) {
                $j->on('ai.id', '=', 'u.id')->where('ai.culture', '=', 'en');
            })
            ->where('c.status', 'pending')
            ->select('c.*', 'u.username', 'u.email', 'ai.authorized_form_of_name as submitted_by_name')
            ->orderByDesc('c.submitted_at');
        if ($locale) {
            $q->where('c.locale', $locale);
        }
        return $q->get();
    }

    private function guardLocale(string $locale): void
    {
        if (!preg_match('/^[a-z][a-z0-9_-]{0,15}$/i', $locale)) {
            throw new \InvalidArgumentException('invalid locale code: ' . $locale);
        }
    }
}
