@extends('theme::layouts.1col')

@section('title', __('Function & Route Catalogues'))
@section('body-class', 'functions-docs index')

@section('content')
<div class="row">
  <div class="col-12">
    <div class="card bg-light mb-4">
      <div class="card-body">
        <h1 class="h3 mb-2"><i class="bi bi-journal-code me-2"></i>{{ __('Function & Route Catalogues') }}</h1>
        <p class="text-muted mb-0">
          {{ __('Browser-rendered surface for the auto-generated function/route catalogues. Source files live at /opt/ai/km/auto_functions_kb*.md and are regenerated by a systemd timer roughly every 10 minutes; this page re-reads them on request and caches parsed sections for 5 minutes.') }}
        </p>
      </div>
    </div>

    <div class="row g-3">
      @foreach($catalogues as $kind => $cat)
        <div class="col-lg-4 col-md-6">
          <div class="card h-100 shadow-sm">
            <div class="card-body d-flex flex-column">
              <div class="d-flex align-items-center mb-2">
                <i class="bi {{ $cat['icon'] ?? 'bi-file-text' }} fs-3 me-2 text-primary"></i>
                <h5 class="card-title mb-0">{{ $cat['label'] ?? ucfirst($kind) }}</h5>
              </div>

              @if(!empty($cat['available']))
                <p class="text-muted small mb-2">
                  <span class="badge bg-secondary me-1">{{ number_format($cat['section_count']) }} {{ \Illuminate\Support\Str::plural($cat['group_label'], $cat['section_count']) }}</span>
                  <span class="badge bg-light text-dark me-1">{{ number_format($cat['byte_size'] / 1024, 0) }} KB</span>
                  @if($cat['paginate'])
                    <span class="badge bg-info">{{ __('paginated') }}</span>
                  @endif
                </p>
                <p class="text-muted small mb-3">
                  <i class="bi bi-clock me-1"></i>{{ __('updated') }}
                  {{ $cat['mtime'] ? \Carbon\Carbon::createFromTimestamp($cat['mtime'])->diffForHumans() : __('unknown') }}
                </p>
                <a href="{{ route('functionsDocs.show', ['kind' => $kind]) }}" class="btn btn-sm atom-btn-white mt-auto">
                  <i class="bi bi-arrow-right-circle me-1"></i>{{ __('Browse') }}
                </a>
              @else
                <p class="text-danger small mb-2">
                  <i class="bi bi-exclamation-triangle me-1"></i>
                  {{ $cat['reason'] ?? __('Not available') }}
                </p>
                <span class="text-muted small mt-auto">{{ __('Source file missing or unreadable.') }}</span>
              @endif
            </div>
          </div>
        </div>
      @endforeach
    </div>

    <div class="alert alert-secondary small mt-4 mb-0">
      <strong>{{ __('Tip') }}:</strong>
      {{ __('These catalogues feed the KM (RAG) corpus too - if you prefer natural-language queries, ask km.theahg.co.za directly. This page is the static browse fallback for ops + external evaluators.') }}
    </div>
  </div>
</div>
@endsection
