@extends('theme::layouts.1col')

@section('title', __('Catalogue not available') . ' - ' . __('Function & Route Catalogues'))
@section('body-class', 'functions-docs missing')

@section('content')
<div class="row">
  <div class="col-lg-8 mx-auto">
    <a href="{{ route('functionsDocs.index') }}" class="d-block mb-3 small">
      <i class="bi bi-arrow-left me-1"></i>{{ __('All catalogues') }}
    </a>

    <div class="card border-warning">
      <div class="card-body">
        <h1 class="h4 mb-3"><i class="bi bi-exclamation-triangle text-warning me-2"></i>{{ __('Catalogue not available') }}</h1>
        <p class="mb-2">
          {{ __('The') }} <strong>{{ $kind }}</strong> {{ __('catalogue source file is missing or unreadable.') }}
        </p>
        @if(!empty($summary['reason']))
          <p class="text-muted small mb-3"><code>{{ $summary['reason'] }}</code></p>
        @endif
        <p class="text-muted small mb-0">
          {{ __('The catalogues are auto-generated by') }} <code>/opt/ai/km/build_functions_kb*.py</code>
          {{ __('via systemd timer (~10 min cycle). If this persists, check that the timer is running on the AI host.') }}
        </p>
      </div>
    </div>
  </div>
</div>
@endsection
