<?php

/**
 * Ead2002Serializer - EAD 2002 XML serializer.
 *
 * Produces the <ead>...</ead> element body for an information object,
 * conforming to the EAD 2002 DTD. Used for both standalone XML downloads
 * and as the metadata body for OAI-PMH dissemination (metadataPrefix oai_ead).
 *
 * Copyright (C) 2026 Johan Pieterse
 * Plain Sailing Information Systems
 *
 * This file is part of Heratio.
 *
 * Heratio is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

namespace AhgMetadataExport\Services\Exporters;

use Illuminate\Support\Facades\DB;

class Ead2002Serializer
{
    use InformationObjectFetcher;

    public function getFormat(): string
    {
        return 'oai_ead';
    }

    public function getSchemaUrl(): string
    {
        return 'http://www.loc.gov/ead/ead.xsd';
    }

    public function getNamespace(): string
    {
        return 'urn:isbn:1-931666-22-9';
    }

    /**
     * Serialize a single information object as EAD 2002 XML.
     * Returns the <ead>...</ead> element with no <?xml?> declaration so it can
     * be embedded inside an OAI-PMH <metadata> wrapper.
     */
    public function serializeRecord(int $objectId, string $culture = 'en', bool $includeChildren = true): string
    {
        $io = $this->fetchIo($objectId, $culture);
        if (!$io) {
            return '';
        }

        $repository  = $this->fetchRepository($io, $culture);
        $events      = $this->fetchEvents($io, $culture);
        $creators    = $this->fetchCreators($io, $culture);
        $subjects    = $this->fetchAccessPoints($io, 35, $culture);
        $places      = $this->fetchAccessPoints($io, 42, $culture);
        $genres      = $this->fetchAccessPoints($io, 78, $culture);
        $notes       = $this->fetchNotes($io, $culture);
        $levelName   = $this->fetchLevelName($io, $culture);
        $children    = $includeChildren ? $this->fetchDescendants($io, $culture) : collect();

        $eadLevel = $this->mapLevelToEad($levelName);
        $dateNormal = gmdate('Y-m-d');
        $date = gmdate('Y-m-d H:i e');

        // Note: schemaLocation rather than DTD so the OAI envelope stays
        // schema-valid; EAD 2002 also has an XSD form (https://www.loc.gov/ead/).
        $xml  = '<ead xmlns="' . $this->getNamespace() . '"';
        $xml .= ' xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"';
        $xml .= ' xsi:schemaLocation="' . $this->getNamespace() . ' ' . $this->getSchemaUrl() . '">' . "\n";

        // Header
        $xml .= "<eadheader langencoding=\"iso639-2b\" countryencoding=\"iso3166-1\" dateencoding=\"iso8601\" repositoryencoding=\"iso15511\" scriptencoding=\"iso15924\" relatedencoding=\"DC\">\n";
        $xml .= "  <eadid>" . $this->escXml($io->identifier) . "</eadid>\n";
        $xml .= "  <filedesc>\n";
        $xml .= "    <titlestmt>\n";
        $xml .= "      <titleproper encodinganalog=\"6\">" . $this->escXml($io->title) . "</titleproper>\n";
        $xml .= "    </titlestmt>\n";
        if ($repository) {
            $xml .= "    <publicationstmt>\n";
            $xml .= "      <publisher encodinganalog=\"8\">" . $this->escXml($repository->name) . "</publisher>\n";
            $xml .= "      <date normal=\"{$dateNormal}\" encodinganalog=\"9\">{$dateNormal}</date>\n";
            $xml .= "    </publicationstmt>\n";
        }
        $xml .= "  </filedesc>\n";
        $xml .= "  <profiledesc>\n";
        $xml .= "    <creation>Generated by Heratio <date normal=\"{$dateNormal}\">{$date}</date></creation>\n";
        $xml .= "    <langusage><language langcode=\"{$culture}\">" . $this->escXml($culture) . "</language></langusage>\n";
        $xml .= "  </profiledesc>\n";
        $xml .= "</eadheader>\n";

        // Archdesc
        $xml .= "<archdesc level=\"{$eadLevel}\" relatedencoding=\"isad\">\n";
        $xml .= $this->buildDidElement($io, $events, $creators, $repository, $culture);

        if ($io->scope_and_content) {
            $xml .= "  <scopecontent encodinganalog=\"3.3.1\"><p>" . $this->escXml($io->scope_and_content) . "</p></scopecontent>\n";
        }
        if ($io->arrangement) {
            $xml .= "  <arrangement encodinganalog=\"3.3.4\"><p>" . $this->escXml($io->arrangement) . "</p></arrangement>\n";
        }
        if ($io->appraisal) {
            $xml .= "  <appraisal encodinganalog=\"3.3.2\"><p>" . $this->escXml($io->appraisal) . "</p></appraisal>\n";
        }
        if ($io->acquisition) {
            $xml .= "  <acqinfo encodinganalog=\"3.2.4\"><p>" . $this->escXml($io->acquisition) . "</p></acqinfo>\n";
        }
        if ($io->accruals) {
            $xml .= "  <accruals encodinganalog=\"3.3.3\"><p>" . $this->escXml($io->accruals) . "</p></accruals>\n";
        }
        if ($io->archival_history) {
            $xml .= "  <custodhist encodinganalog=\"3.2.3\"><p>" . $this->escXml($io->archival_history) . "</p></custodhist>\n";
        }
        if ($io->physical_characteristics) {
            $xml .= "  <phystech encodinganalog=\"3.4.4\"><p>" . $this->escXml($io->physical_characteristics) . "</p></phystech>\n";
        }
        if ($io->location_of_originals) {
            $xml .= "  <originalsloc encodinganalog=\"3.5.1\"><p>" . $this->escXml($io->location_of_originals) . "</p></originalsloc>\n";
        }
        if ($io->location_of_copies) {
            $xml .= "  <altformavail encodinganalog=\"3.5.2\"><p>" . $this->escXml($io->location_of_copies) . "</p></altformavail>\n";
        }
        if ($io->related_units_of_description) {
            $xml .= "  <relatedmaterial encodinganalog=\"3.5.3\"><p>" . $this->escXml($io->related_units_of_description) . "</p></relatedmaterial>\n";
        }
        if ($io->access_conditions) {
            $xml .= "  <accessrestrict encodinganalog=\"3.4.1\"><p>" . $this->escXml($io->access_conditions) . "</p></accessrestrict>\n";
        }
        if ($io->reproduction_conditions) {
            $xml .= "  <userestrict encodinganalog=\"3.4.2\"><p>" . $this->escXml($io->reproduction_conditions) . "</p></userestrict>\n";
        }
        if ($io->finding_aids) {
            $xml .= "  <otherfindaid encodinganalog=\"3.4.5\"><p>" . $this->escXml($io->finding_aids) . "</p></otherfindaid>\n";
        }

        // Control access
        if ($subjects->isNotEmpty() || $places->isNotEmpty() || $genres->isNotEmpty()) {
            $xml .= "  <controlaccess>\n";
            foreach ($subjects as $s) {
                $xml .= "    <subject>" . $this->escXml($s->name) . "</subject>\n";
            }
            foreach ($places as $p) {
                $xml .= "    <geogname>" . $this->escXml($p->name) . "</geogname>\n";
            }
            foreach ($genres as $g) {
                $xml .= "    <genreform>" . $this->escXml($g->name) . "</genreform>\n";
            }
            $xml .= "  </controlaccess>\n";
        }

        // Children
        if ($includeChildren && $children->isNotEmpty()) {
            $xml .= "  <dsc type=\"combined\">\n";
            $nestedRgt = [];
            foreach ($children as $child) {
                while (count($nestedRgt) > 0 && $child->rgt > $nestedRgt[count($nestedRgt) - 1]) {
                    array_pop($nestedRgt);
                    $xml .= "    </c>\n";
                }
                $childLevel = $child->level_of_description_id
                    ? $this->mapLevelToEad(DB::table('term_i18n')->where('id', $child->level_of_description_id)->where('culture', $culture)->value('name'))
                    : 'otherlevel';
                $xml .= "    <c level=\"{$childLevel}\">\n";
                $xml .= "      <did>\n";
                if ($child->identifier) {
                    $xml .= "        <unitid>" . $this->escXml($child->identifier) . "</unitid>\n";
                }
                $xml .= "        <unittitle>" . $this->escXml($child->title) . "</unittitle>\n";
                if ($child->extent_and_medium) {
                    $xml .= "        <physdesc><extent>" . $this->escXml($child->extent_and_medium) . "</extent></physdesc>\n";
                }
                $xml .= "      </did>\n";
                if ($child->scope_and_content) {
                    $xml .= "      <scopecontent><p>" . $this->escXml($child->scope_and_content) . "</p></scopecontent>\n";
                }
                if ($child->arrangement) {
                    $xml .= "      <arrangement><p>" . $this->escXml($child->arrangement) . "</p></arrangement>\n";
                }
                if ($child->rgt == $child->lft + 1) {
                    $xml .= "    </c>\n";
                } else {
                    $nestedRgt[] = $child->rgt;
                }
            }
            while (count($nestedRgt) > 0) {
                array_pop($nestedRgt);
                $xml .= "    </c>\n";
            }
            $xml .= "  </dsc>\n";
        }

        $xml .= "</archdesc>\n</ead>";
        return $xml;
    }

    private function buildDidElement($io, $events, $creators, $repository, string $culture): string
    {
        $xml = "  <did>\n";
        if ($io->identifier) {
            $xml .= "    <unitid encodinganalog=\"3.1.1\">" . $this->escXml($io->identifier) . "</unitid>\n";
        }
        $xml .= "    <unittitle encodinganalog=\"3.1.2\">" . $this->escXml($io->title) . "</unittitle>\n";

        foreach ($events as $event) {
            $dateStr = $event->date_display ?? '';
            $normal = '';
            if ($event->start_date && $event->end_date) {
                $normal = $event->start_date . '/' . $event->end_date;
            } elseif ($event->start_date) {
                $normal = $event->start_date;
            }
            if (!$dateStr && !$normal) {
                continue;
            }
            $xml .= "    <unitdate";
            if ($normal) {
                $xml .= " normal=\"" . $this->escXml($normal) . "\"";
            }
            $xml .= " encodinganalog=\"3.1.3\">" . $this->escXml($dateStr ?: $normal) . "</unitdate>\n";
        }

        foreach ($creators as $creator) {
            $tag = match ((int) ($creator->entity_type_id ?? 0)) {
                132 => 'persname', 130 => 'famname', 131 => 'corpname', default => 'name',
            };
            $xml .= "    <origination encodinganalog=\"3.2.1\"><{$tag}>" . $this->escXml($creator->name) . "</{$tag}></origination>\n";
        }

        if ($io->extent_and_medium) {
            $xml .= "    <physdesc encodinganalog=\"3.1.5\"><extent>" . $this->escXml($io->extent_and_medium) . "</extent></physdesc>\n";
        }

        if ($repository) {
            $xml .= "    <repository><corpname>" . $this->escXml($repository->name) . "</corpname></repository>\n";
        }

        $xml .= "  </did>\n";
        return $xml;
    }
}
