@extends('theme::layouts.1col')
@section('title', 'Vendors')
@section('content')
@php $types = \Illuminate\Support\Facades\DB::table('ahg_dropdown')->where('taxonomy','library_vendor_type')->where('is_active',1)->orderBy('sort_order')->get(['code','label']); @endphp
<div class="container py-4">
<div class="d-flex justify-content-between align-items-center mb-3"><h1 class="mb-0"><i class="fas fa-truck me-2"></i>{{ __('Vendors') }}</h1><div><a href="{{ route('library.acquisitions') }}" class="btn btn-outline-secondary"><i class="fas fa-list me-1"></i>{{ __('Orders') }}</a> <a href="{{ route('library.acquisition-vendor-create') }}" class="btn atom-btn-white"><i class="fas fa-plus me-1"></i>{{ __('New Vendor') }}</a></div></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if(session('info'))<div class="alert alert-info">{{ session('info') }}</div>@endif
<form method="get" class="row g-2 mb-3"><div class="col-md-4"><input type="text" name="q" class="form-control" placeholder="{{ __('Search name, code, contact') }}" value="{{ e($searchQuery??'') }}"></div><div class="col-md-3"><select name="type" class="form-select"><option value="">{{ __('All types') }}</option>@foreach($types as $t)<option value="{{ $t->code }}" {{ ($typeFilter??'')===$t->code?'selected':'' }}>{{ $t->label }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="fas fa-search me-1"></i>{{ __('Filter') }}</button></div></form>
<div class="card"><div class="card-body p-0"><table class="table table-striped mb-0"><thead><tr><th>{{ __('Name') }}</th><th>{{ __('Code') }}</th><th>{{ __('Type') }}</th><th>{{ __('Contact') }}</th><th>{{ __('Country') }}</th><th>{{ __('Active') }}</th><th></th></tr></thead><tbody>@forelse($vendors??[] as $v)<tr><td><strong>{{ e($v->name??'') }}</strong></td><td>{{ e($v->vendor_code??'') }}</td><td>{{ e($v->vendor_type??'') }}</td><td>{{ e($v->contact_name??'') }} @if($v->email??null)<a href="mailto:{{ e($v->email) }}"><i class="fas fa-envelope"></i></a>@endif</td><td>{{ e($v->country??'') }}</td><td>@if($v->is_active??0)<span class="badge bg-success">{{ __('Yes') }}</span>@else<span class="badge bg-secondary">{{ __('No') }}</span>@endif</td><td class="text-end"><a href="{{ route('library.acquisition-vendor-edit',$v->id) }}" class="btn btn-sm btn-outline-secondary"><i class="fas fa-edit"></i></a></td></tr>@empty<tr><td colspan="7" class="text-muted text-center py-4">{{ __('No vendors found.') }}</td></tr>@endforelse</tbody></table></div></div>
</div>
@endsection
