{{-- Review Studio - reviewer-twin run detail - Research OS Stage 14 (heratio#1230) --}}
@extends('theme::layouts.2col')

@section('sidebar')
    @include('research::research._sidebar', ['sidebarActive' => 'projects'])
@endsection

@section('title', 'Reviewer simulation')

@php
    $findingGroups = $findingGroups ?? [];
    $aiLabel       = $aiLabel ?? 'AI reviewer - via the AHG gateway, not a human reviewer';
    $findings      = (isset($run->findings_decoded) && is_array($run->findings_decoded)) ? $run->findings_decoded : [];
    // Bootstrap accent per group for a quick visual read.
    $groupColours = [
        'major_concerns'         => 'danger',
        'minor_concerns'         => 'warning',
        'likely_objections'      => 'warning',
        'required_revisions'     => 'primary',
        'rejection_risks'        => 'danger',
        'strongest_contribution' => 'success',
        'weakest_section'        => 'warning',
        'missing_literature'     => 'info',
    ];
    $anyFinding = false;
    foreach ($findings as $list) { if (!empty($list)) { $anyFinding = true; break; } }
@endphp

@section('content')
<nav aria-label="{{ __('breadcrumb') }}">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{{ route('research.dashboard') }}">{{ __('Research') }}</a></li>
        <li class="breadcrumb-item"><a href="{{ route('research.viewProject', $project->id ?? 0) }}">{{ e($project->title ?? '') }}</a></li>
        <li class="breadcrumb-item"><a href="{{ route('research.review.index', $project->id ?? 0) }}">{{ __('Review Studio') }}</a></li>
        <li class="breadcrumb-item active">{{ __('Simulation') }}</li>
    </ol>
</nav>

@if(session('error'))
    <div class="alert alert-danger alert-dismissible fade show">{{ session('error') }}<button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>
@endif

<div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="h3">
        <i class="fas fa-robot text-secondary me-2"></i>{{ __('Reviewer simulation') }}
        <span class="badge bg-secondary align-middle">{{ $run->persona_label ?? $run->persona }}</span>
    </h1>
    <a href="{{ route('research.review.index', $project->id) }}" class="btn btn-outline-secondary btn-sm"><i class="fas fa-arrow-left me-1"></i>{{ __('Back') }}</a>
</div>

{{-- Mandatory AI provenance label --}}
<div class="alert alert-secondary">
    <i class="fas fa-robot me-1"></i><strong>{{ $aiLabel }}.</strong>
    {{ __('This critique was generated by a language model and may be wrong, incomplete, or overstated. Use it to stress-test your work; it is not a peer-review outcome.') }}
    @if(!empty($run->model))
        <span class="d-block small mt-1"><i class="fas fa-microchip me-1"></i>{{ __('Model') }}: {{ e($run->model) }}</span>
    @endif
    <span class="d-block small mt-1"><i class="fas fa-clock me-1"></i>{{ \Illuminate\Support\Carbon::parse($run->created_at)->format('Y-m-d H:i') }} &middot; {{ e($run->author_name ?? '') }}</span>
</div>

@if(!empty($run->summary))
    <div class="card mb-4">
        <div class="card-header fw-bold">{{ __('Summary') }}</div>
        <div class="card-body" style="white-space:pre-line">{{ e($run->summary) }}</div>
    </div>
@endif

@if($anyFinding)
    <div class="row g-3">
        @foreach($findingGroups as $key => $label)
            @php $items = $findings[$key] ?? []; @endphp
            @if(!empty($items))
                @php $colour = $groupColours[$key] ?? 'secondary'; @endphp
                <div class="col-md-6">
                    <div class="card border-{{ $colour }} h-100">
                        <div class="card-header bg-{{ $colour }}-subtle fw-bold">{{ $label }}</div>
                        <div class="card-body p-0">
                            <ul class="list-group list-group-flush">
                                @foreach($items as $item)
                                    <li class="list-group-item small">{{ e($item) }}</li>
                                @endforeach
                            </ul>
                        </div>
                    </div>
                </div>
            @endif
        @endforeach
    </div>
@elseif(empty($run->summary))
    <div class="text-center py-5 text-muted">
        <i class="fas fa-robot fa-2x mb-2 d-block opacity-50"></i>
        {{ __('This run produced no structured findings. The AI reply may have been empty or unparseable.') }}
    </div>
@endif
@endsection
