<?php

use Illuminate\Support\Facades\Route;

Route::prefix('admin/privacy')->middleware(['web'])->group(function () {
    Route::get('/complaint-confirmation', [\::class, 'complaintConfirmation'])->name('ahgprivacy.complaint-confirmation');
    Route::get('/complaint', [\::class, 'complaint'])->name('ahgprivacy.complaint');
    Route::get('/dashboard', [\::class, 'dashboard'])->name('ahgprivacy.dashboard');
    Route::get('/dsar-confirmation', [\::class, 'dsarConfirmation'])->name('ahgprivacy.dsar-confirmation');
    Route::get('/dsar-request', [\::class, 'dsarRequest'])->name('ahgprivacy.dsar-request');
    Route::get('/dsar-status', [\::class, 'dsarStatus'])->name('ahgprivacy.dsar-status');
    Route::get('/index', [\::class, 'index'])->name('ahgprivacy.index');
    Route::get('/breach-add', [\::class, 'breachAdd'])->name('ahgprivacy.breach-add');
    Route::get('/breach-edit', [\::class, 'breachEdit'])->name('ahgprivacy.breach-edit');
    Route::get('/breach-list', [\::class, 'breachList'])->name('ahgprivacy.breach-list');
    Route::get('/breach-view', [\::class, 'breachView'])->name('ahgprivacy.breach-view');
    Route::get('/complaint-add', [\::class, 'complaintAdd'])->name('ahgprivacy.complaint-add');
    Route::get('/complaint-edit', [\::class, 'complaintEdit'])->name('ahgprivacy.complaint-edit');
    Route::get('/complaint-list', [\::class, 'complaintList'])->name('ahgprivacy.complaint-list');
    Route::get('/complaint-view', [\::class, 'complaintView'])->name('ahgprivacy.complaint-view');
    Route::get('/config', [\::class, 'config'])->name('ahgprivacy.config');
    Route::get('/consent-add', [\::class, 'consentAdd'])->name('ahgprivacy.consent-add');
    Route::get('/consent-edit', [\::class, 'consentEdit'])->name('ahgprivacy.consent-edit');
    Route::get('/consent-list', [\::class, 'consentList'])->name('ahgprivacy.consent-list');
    Route::get('/consent-view', [\::class, 'consentView'])->name('ahgprivacy.consent-view');
    Route::get('/dsar-add', [\::class, 'dsarAdd'])->name('ahgprivacy.dsar-add');
    Route::get('/dsar-edit', [\::class, 'dsarEdit'])->name('ahgprivacy.dsar-edit');
    Route::get('/dsar-list', [\::class, 'dsarList'])->name('ahgprivacy.dsar-list');
    Route::get('/dsar-view', [\::class, 'dsarView'])->name('ahgprivacy.dsar-view');
    Route::get('/jurisdiction-add', [\::class, 'jurisdictionAdd'])->name('ahgprivacy.jurisdiction-add');
    Route::get('/jurisdiction-edit', [\::class, 'jurisdictionEdit'])->name('ahgprivacy.jurisdiction-edit');
    Route::get('/jurisdiction-info', [\::class, 'jurisdictionInfo'])->name('ahgprivacy.jurisdiction-info');
    Route::get('/jurisdiction-list', [\::class, 'jurisdictionList'])->name('ahgprivacy.jurisdiction-list');
    Route::get('/jurisdictions', [\::class, 'jurisdictions'])->name('ahgprivacy.jurisdictions');
    Route::get('/notifications', [\::class, 'notifications'])->name('ahgprivacy.notifications');
    Route::get('/officer-add', [\::class, 'officerAdd'])->name('ahgprivacy.officer-add');
    Route::get('/officer-edit', [\::class, 'officerEdit'])->name('ahgprivacy.officer-edit');
    Route::get('/officer-list', [\::class, 'officerList'])->name('ahgprivacy.officer-list');
    Route::get('/paia-add', [\::class, 'paiaAdd'])->name('ahgprivacy.paia-add');
    Route::get('/paia-list', [\::class, 'paiaList'])->name('ahgprivacy.paia-list');
    Route::get('/pii-review', [\::class, 'piiReview'])->name('ahgprivacy.pii-review');
    Route::get('/pii-scan-object', [\::class, 'piiScanObject'])->name('ahgprivacy.pii-scan-object');
    Route::get('/pii-scan', [\::class, 'piiScan'])->name('ahgprivacy.pii-scan');
    Route::get('/report', [\::class, 'report'])->name('ahgprivacy.report');
    Route::get('/ropa-add', [\::class, 'ropaAdd'])->name('ahgprivacy.ropa-add');
    Route::get('/ropa-edit', [\::class, 'ropaEdit'])->name('ahgprivacy.ropa-edit');
    Route::get('/ropa-list', [\::class, 'ropaList'])->name('ahgprivacy.ropa-list');
    Route::get('/ropa-view', [\::class, 'ropaView'])->name('ahgprivacy.ropa-view');
    Route::get('/visual-redaction-editor', [\::class, 'visualRedactionEditor'])->name('ahgprivacy.visual-redaction-editor');
});
