<?php

/**
 * @author    Johan Pieterse <johan@plainsailingisystems.co.za>
 * @copyright Plain Sailing Information Systems
 * @license   AGPL-3.0-or-later
 */

namespace AhgLibrary\Services;

use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Throwable;

/**
 * Notification delivery for serials (heratio#1092).
 *
 * Two channels:
 *   - Claim alerts: an expected issue has gone overdue past its claim window.
 *   - Expiry alerts: a subscription is within N days of its subscription_end.
 *
 * Email is delivered via the Laravel Mail facade (Mail::raw, same low-dependency
 * approach as EmailUsageReportsCommand). SMS is gated behind config and is a
 * best-effort log-only stub unless a real gateway is wired - so no SMS is ever
 * sent silently. All sends are best-effort and never throw to the caller; a
 * failed send is logged and reported back in the return value.
 */
class LibrarySerialNotificationService
{
    public function __construct(private LibrarySerialService $serials)
    {
    }

    /**
     * Resolve the recipient for a serial: explicit subscription
     * notification_email, else the global fallback in config
     * (ahg-library.serials.default_notification_email), else null.
     */
    public function resolveRecipient(?string $subscriptionEmail): ?string
    {
        $email = $subscriptionEmail ?: (string) config('ahg-library.serials.default_notification_email', '');
        $email = trim($email);

        return filter_var($email, FILTER_VALIDATE_EMAIL) ? $email : null;
    }

    /**
     * Send a claim alert for an overdue serial issue. Returns true when an email
     * was dispatched (or would have been, in the absence of a recipient the
     * method returns false). Records a claim row when $recordClaim is true.
     *
     * @param array{serial:object,predicted_date:string,days_late:int,subscription_end:?string} $claim
     */
    public function sendClaimAlert(array $claim, ?string $recipient, bool $recordClaim = true): bool
    {
        $serial = $claim['serial'];
        $to = $this->resolveRecipient($recipient);

        $reason = sprintf(
            'Expected issue (predicted %s) is %d day(s) overdue.',
            $claim['predicted_date'] ?? '?',
            (int) ($claim['days_late'] ?? 0)
        );

        if ($recordClaim) {
            $this->serials->recordClaim(
                (int) $serial->id,
                null,
                $reason,
                'system:claim-alert',
                $to ? 'sent' : 'open'
            );
        }

        if (!$to) {
            return false;
        }

        $subject = sprintf('[Heratio Serials] Claim: %s', $serial->title ?? ('Serial #' . $serial->id));
        $body = sprintf(
            "A serial issue appears to be missing and may need to be claimed from the supplier.\n\n"
            . "Title:    %s\nISSN:     %s\nPredicted issue date: %s\nDays overdue:         %d\n\n"
            . "Please follow up with the vendor.\n\nGenerated by Heratio on %s.\n",
            $serial->title ?? '',
            $serial->issn ?? '',
            $claim['predicted_date'] ?? '?',
            (int) ($claim['days_late'] ?? 0),
            now()->toIso8601String()
        );

        $sent = $this->send($to, $subject, $body);
        $this->maybeSendSms($to, $subject);

        return $sent;
    }

    /**
     * Send a subscription-expiry warning. Returns true when an email was sent.
     *
     * @param array{serial:object,subscription_end:string,days_until:int,notification_email:?string} $row
     */
    public function sendExpiryAlert(array $row): bool
    {
        $serial = $row['serial'];
        $to = $this->resolveRecipient($row['notification_email'] ?? null);
        if (!$to) {
            return false;
        }

        $subject = sprintf('[Heratio Serials] Subscription expiring: %s', $serial->title ?? ('Serial #' . $serial->id));
        $body = sprintf(
            "A serial subscription is approaching its end date.\n\n"
            . "Title:        %s\nISSN:         %s\nExpires:      %s\nDays remaining: %d\n\n"
            . "Renew before the end date to avoid a gap in holdings.\n\nGenerated by Heratio on %s.\n",
            $serial->title ?? '',
            $serial->issn ?? '',
            $row['subscription_end'],
            (int) ($row['days_until'] ?? 0),
            now()->toIso8601String()
        );

        $sent = $this->send($to, $subject, $body);
        $this->maybeSendSms($to, $subject);

        return $sent;
    }

    /**
     * Low-level email send (best-effort, never throws).
     */
    private function send(string $to, string $subject, string $body): bool
    {
        try {
            Mail::raw($body, function ($m) use ($to, $subject) {
                $m->to($to)->subject($subject);
            });
            return true;
        } catch (Throwable $e) {
            Log::warning('LibrarySerialNotificationService email failed: ' . $e->getMessage());
            return false;
        }
    }

    /**
     * SMS is opt-in via config (ahg-library.serials.sms_enabled) and requires a
     * gateway wiring. With no gateway configured this logs intent only - it
     * never sends silently and never throws.
     */
    private function maybeSendSms(string $context, string $message): void
    {
        if (!config('ahg-library.serials.sms_enabled', false)) {
            return;
        }

        // No SMS gateway is bundled with Heratio (AI/comms are remote-only).
        // When a gateway is wired, dispatch here. Until then, log intent.
        Log::info("LibrarySerial SMS (gated) would send: {$message} [{$context}]");
    }
}
